# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Annotated, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnRawBasePanel, KbnRawBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone


class KbnRawBaseLink(BaseRawVwModel):
    id: str | None = Field(default=None)
    """The unique identifier for the link."""

    order: int | None = Field(default=None)
    """Order of the link in the list."""

    label: Annotated[str | None, OmitIfNone()] = Field(default=None)
    """Friendly label for the link. Optional, can be used for display purposes."""


type KbnRawLinkTypes = KbnRawDashboardLink | KbnRawWebLink


class KbnRawDashboardLinkOptions(BaseRawVwModel):
    """Options for a dashboard link in the Kibana Links panel."""

    openInNewTab: bool | None = Field(default=None)
    """If `true`, the link will open in a new browser tab."""

    useCurrentDateRange: bool | None = Field(default=None)
    """If `true`, the link will use the current date range when navigating to the dashboard."""

    useCurrentFilters: bool | None = Field(default=None)
    """If `true`, the link will use the current filters when navigating to the dashboard."""


class KbnRawDashboardLink(KbnRawBaseLink):
    """Represents a link to a dashboard."""

    type: Literal['dashboardLink'] = 'dashboardLink'
    """Type of the link, specifically for dashboard links."""

    options: Annotated[KbnRawDashboardLinkOptions | None, OmitIfNone()] = Field(default=None)
    """Options for the dashboard link, such as whether to open in a new tab or use current filters."""

    destinationRefName: str | None = Field(default=None)
    """Reference name for the destination dashboard."""


class KbnRawWebLinkOptions(BaseRawVwModel):
    """Options for a web link in the Kibana Links panel."""

    openInNewTab: bool | None = Field(default=None)
    """If `true`, the link will open in a new browser tab."""

    encodeUrl: bool | None = Field(default=None)
    """If `true`, the URL will be URL-encoded when navigating to the external resource."""


class KbnRawWebLink(KbnRawBaseLink):
    """Represents a link to an external web resource."""

    type: Literal['externalLink'] = 'externalLink'
    """Type of the link, specifically for web links."""

    options: Annotated[KbnRawWebLinkOptions | None, OmitIfNone()] = Field(default=None)

    destination: str | None = Field(default=None)
    """The URL to which the link points."""


class KbnRawLinksPanelAttributes(BaseRawVwModel):
    layout: Literal['horizontal', 'vertical'] | None = None
    links: list[KbnRawLinkTypes] = Field(default_factory=list)


class KbnRawLinksPanelEmbeddableConfig(KbnRawBasePanelEmbeddableConfig):
    attributes: KbnRawLinksPanelAttributes | None = None


class KbnRawLinksPanel(KbnRawBasePanel):
    """Represents a Links panel in the Kibana Kbn structure."""

    type: Literal['links'] = 'links'
    embeddableConfig: KbnRawLinksPanelEmbeddableConfig | None = None
