[project]
name = "kb-dashboard-workspace"
version = "0.1.10"
description = "Root workspace for kb-yaml-to-lens project"
readme = "./README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Code Generators",
]

dependencies = [
    "kb-dashboard-compiler",
    "kb-dashboard-lsp",
]

[tool.uv.sources]
kb-dashboard-core = { workspace = true }
kb-dashboard-cli = { workspace = true }
kb-dashboard-lsp = { workspace = true }
kb-dashboard-tools = { workspace = true }
kb-dashboard-compiler = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/kb-dashboard-core",
    "packages/kb-dashboard-cli",
    "packages/kb-dashboard-lsp",
    "packages/kb-dashboard-tools",
    "packages/kb-dashboard-compiler",
]

[dependency-groups]
docs = [
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.32",
    "mkdocstrings[python]>=1.0.0",
    "pymdown-extensions>=10.0",
    "griffe-pydantic>=1.1.8",
    "griffe-fieldz>=0.4.0",
    "mkdocs-click>=0.8.0",
]
dev = [
    "pytest>=9.0",
    "pytest-cov>=6.0",
    "pytest-freezer>=0.4.9",
    "deepdiff>=8.4.2",
    "ruff>=0.14",
    "pytest-asyncio>=1.3",
    "basedpyright>=1.36",
    "inline-snapshot>=0.31.1",
    "pytest-check-links>=0.9.0",
    "dirty-equals>=0.8.0",
    "pytest-examples>=0.0.18",
    "yamlfix>=1.17.0",
]
