# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Literal

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnBasePanel, KbnBasePanelEmbeddableConfig


class KbnSearchEmbeddableConfig(KbnBasePanelEmbeddableConfig):
    savedObjectId: str | None = None


class KbnSearchPanel(KbnBasePanel):
    """Represents a Search panel in the Kibana JSON structure."""

    type: Literal['search'] = 'search'
    panelRefName: str | None = None
    embeddableConfig: KbnSearchEmbeddableConfig | None = None
