# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive base model and shared types for kbn_raw_models."""

from typing import ClassVar

from kb_dashboard_core.shared.view import OmitIfNone, RootDict  # re-exports for generated modules
from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict, Field

__all__ = ['BaseRawVwModel', 'KbnReference', 'OmitIfNone', 'RootDict']


class BaseRawVwModel(PydanticBaseModel):
    """Permissive base for raw Kibana view models — extra fields are ignored, strict mode off."""

    model_config: ClassVar[ConfigDict] = ConfigDict(
        strict=False,
        extra='ignore',
        frozen=False,
        populate_by_name=True,
        use_enum_values=True,
    )


class KbnReference(BaseRawVwModel):
    """Permissive reference — type/id/name are all optional since real dashboards may omit fields."""

    type: str | None = Field(default=None)
    id: str | None = Field(default=None)
    name: str | None = Field(default=None)
