# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Raw permissive KbnRaw* view models for kb_dashboard_core shared types."""

from typing import ClassVar, TypeVar

from kb_dashboard_core.shared.view import OmitIfNone, RootDict  # re-export for generated modules
from pydantic import BaseModel as PydanticBaseModel
from pydantic import ConfigDict, Field

__all__ = ['BaseRawVwModel', 'KbnRawReference', 'OmitIfNone', 'RootDict']

T = TypeVar('T')


class BaseRawVwModel(PydanticBaseModel):
    """Permissive base for raw Kibana view models — extra fields are ignored, strict mode off."""

    model_config: ClassVar[ConfigDict] = ConfigDict(
        strict=False,
        extra='ignore',
        frozen=False,
        populate_by_name=True,
        use_enum_values=True,
    )


class KbnRawReference(BaseRawVwModel):
    """Represents a reference object in the Kibana JSON structure."""

    type: str = Field(default='')
    """The type of the referenced object, e.g., 'index-pattern', 'visualization', 'dashboard'."""

    id: str = Field(default='')
    """The unique or friendly identifier of the referenced object."""

    name: str = Field(default='')
    """A sometimes namespaced identifier for the reference."""
