# GitHub Actions Workflow: Build and Publish Kibana Fixture Generator Image
#
# This workflow builds Docker images with bootstrapped Kibana and publishes them to GHCR.
# It can be triggered:
# 1. Manually via workflow_dispatch (for specific Kibana versions)
# 2. On a schedule (to build latest Kibana version automatically)
# 3. On push to main (when Dockerfile.ghcr changes)
#
# Images are tagged with the Kibana version (e.g., main, v9.4.0, v8.15.3)
# and cached in GHCR to avoid rebuilding unnecessarily.

name: Build Kibana Fixture Generator Image

on:
  # Allow manual triggering with custom Kibana version
  workflow_dispatch:
    inputs:
      kibana_version:
        description: 'Kibana version/branch to build (e.g., main, v9.4.0, v8.15.3)'
        required: true
        default: 'main'
        type: string
      force_rebuild:
        description: 'Force rebuild even if image exists'
        required: false
        default: false
        type: boolean
  
  # Run weekly to keep latest version fresh
  schedule:
    # Run every Monday at 2 AM UTC
    - cron: '0 2 * * 1'
  
  # Rebuild when Dockerfile changes
  push:
    branches: [ main ]
    paths:
      - 'fixture-generator/Dockerfile.ghcr'
      - '.github/workflows/build-kibana-fixture-image.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/kibana-fixture-generator

jobs:
  # Job 1: Determine which Kibana version to build
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      kibana_version: ${{ steps.get-version.outputs.version }}
      should_build: ${{ steps.check-image.outputs.should_build }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Determine Kibana version
        id: get-version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            # Manual trigger: use specified version
            VERSION="${{ github.event.inputs.kibana_version }}"
          elif [ "${{ github.event_name }}" = "schedule" ]; then
            # Scheduled: fetch latest Kibana version
            # Query GitHub API for latest Kibana release or use 'main'
            LATEST=$(curl -s https://api.github.com/repos/elastic/kibana/releases/latest | jq -r '.tag_name // "main"')
            VERSION="${LATEST}"
          else
            # Push event: use main
            VERSION="main"
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Building Kibana version: ${VERSION}"
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if image already exists
        id: check-image
        run: |
          VERSION="${{ steps.get-version.outputs.version }}"
          FORCE_REBUILD="${{ github.event.inputs.force_rebuild }}"
          
          # Default to false if not set (for scheduled/push events)
          if [ -z "$FORCE_REBUILD" ]; then
            FORCE_REBUILD="false"
          fi
          
          # Check if image exists in GHCR
          if docker manifest inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} > /dev/null 2>&1; then
            if [ "$FORCE_REBUILD" = "true" ]; then
              echo "should_build=true" >> $GITHUB_OUTPUT
              echo "Image exists but force rebuild requested"
            else
              echo "should_build=false" >> $GITHUB_OUTPUT
              echo "Image already exists and force rebuild not requested"
            fi
          else
            echo "should_build=true" >> $GITHUB_OUTPUT
            echo "Image does not exist, will build"
          fi

  # Job 2: Report when no build is needed
  skip-build:
    runs-on: ubuntu-latest
    needs: determine-version
    if: needs.determine-version.outputs.should_build == 'false'
    steps:
      - name: Report skip
        run: |
          VERSION="${{ needs.determine-version.outputs.kibana_version }}"
          echo "## Build Skipped" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Kibana Version:** ${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "**Reason:** Image already exists in GHCR" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To force rebuild, trigger workflow with \`force_rebuild: true\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Existing Image" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

  # Job 3: Build and push Docker image
  build-and-push:
    runs-on: ubuntu-latest
    needs: determine-version
    if: needs.determine-version.outputs.should_build == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ needs.determine-version.outputs.kibana_version }}
            type=raw,value=latest,enable=${{ needs.determine-version.outputs.kibana_version == 'main' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fixture-generator
          file: ./fixture-generator/Dockerfile.ghcr
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            KIBANA_VERSION=${{ needs.determine-version.outputs.kibana_version }}
            NODE_VERSION=22.21.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Verify image
        run: |
          VERSION="${{ needs.determine-version.outputs.kibana_version }}"
          echo "Pulling image to verify..."
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}
          
          echo "Testing LensConfigBuilder availability..."
          docker run --rm ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} \
            node -e "require('@kbn/lens-embeddable-utils/config_builder'); console.log('✓ LensConfigBuilder verified')"
      
      - name: Image summary
        run: |
          VERSION="${{ needs.determine-version.outputs.kibana_version }}"
          echo "## Kibana Fixture Generator Image Built Successfully" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Kibana Version:** ${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "**Image Tag:** \`${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Usage" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}" >> $GITHUB_STEP_SUMMARY
          echo "docker run -v ./examples:/tool/examples -v ./output:/tool/output \\" >> $GITHUB_STEP_SUMMARY
          echo "  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION} \\" >> $GITHUB_STEP_SUMMARY
          echo "  node examples/metric-basic.js" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
