name: Claude Code Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  prepare:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '@claude'))
    runs-on: ubuntu-latest
    outputs:
      prompt: ${{ steps.build-prompt.outputs.PROMPT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build prompt
        id: build-prompt
        run: |
          cat >> $GITHUB_OUTPUT << 'PROMPT_END'
          PROMPT<<EOF
          $(cat github/prompts/project-intro.md)

          # Getting Started
          1. Call the generate_agents_md tool to get a high-level summary of the project you're working in
          2. Get the ${{ github.event_name == 'issues' && 'issue' || 'pull request' }} ${{ github.event.issue.number || github.event.pull_request.number }} in the GitHub repository: ${{ github.repository }}.
          3. Don't forget about your MCP tools to call search_code, get_files, etc. to search the repository and other repositories to identify the related classes, methods, docs, tests, etc that are relevant to the code.
          4. Be Thorough! Go the extra mile! Do great work!
          5. If anything you needed or wanted to do during your work was not possible, document the problem in a `Problems Encountered` section
          of your response. Especially if it was something you were asked to do like research the web, run tests, lint, etc.

          $(cat github/prompts/resolve-threads.md)
          EOF
          PROMPT_END

  claude:
    needs: prepare
    uses: ./.github/workflows/run-claude.yml
    with:
      prompt: ${{ needs.prepare.outputs.prompt }}
      allowed-tools: mcp__repository-summary,mcp__code-search,mcp__github-research,WebSearch,WebFetch,Bash(make:*,gh:api:*)
    secrets:
      claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
