name: Claude CodeRabbit Response

on:
  pull_request_review:
    types: [submitted]

concurrency:
  group: claude-coderabbit-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  claude-coderabbit-response:
    if: |
      github.event.review.user.login == 'coderabbitai[bot]' &&
      (github.event.review.state == 'commented' || github.event.review.state == 'changes_requested') &&
      !github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Set CodeRabbit response prompt
        id: prompt
        run: |
          cat >> $GITHUB_OUTPUT << 'EOF'
          PROMPT<<PROMPT_END
          You're a code assistant for kb-yaml-to-lens responding to CodeRabbit review feedback.

          # YOUR TASK

          CodeRabbit has left review feedback on PR #${{ github.event.pull_request.number }}.
          Review ID: ${{ github.event.review.id }}

          Your goal is to:
          1. Fetch all review comments from CodeRabbit for this PR
          2. Address each comment by making appropriate code changes
          3. Resolve review threads after fixing issues
          4. Run tests/linting to verify fixes
          5. Document what was fixed and what couldn't be fixed

          # GETTING STARTED

          1. Call the generate_agents_md tool to understand the project structure
          2. Fetch review threads using GitHub GraphQL API:
             ```bash
             gh api graphql -f query='
               query {
                 repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
                   pullRequest(number: ${{ github.event.pull_request.number }}) {
                     reviewThreads(first: 100) {
                       nodes {
                         id
                         isResolved
                         isOutdated
                         path
                         line
                         comments(first: 10) {
                           nodes {
                             id
                             body
                             author { login }
                             createdAt
                           }
                         }
                       }
                     }
                   }
                 }
               }'
             ```
          3. Filter threads to only those from coderabbitai[bot] that are unresolved

          # ADDRESSING FEEDBACK

          For each unresolved CodeRabbit comment:
          1. Read the file and understand the context
          2. Make the suggested change (or a better alternative if you disagree)
          3. Document your reasoning if you deviate from the suggestion
          4. After all changes, run: `make lint` and `make test`
          5. Fix any failures caused by your changes

          # RESOLVING THREADS

          After successfully addressing a comment:
          ```bash
          gh api graphql -f query='
            mutation {
              resolveReviewThread(input: {threadId: "THREAD_ID"}) {
                thread { id isResolved }
              }
            }'
          ```

          # REPORTING

          After all changes, comment on the PR with a summary:
          - âœ… Comments addressed (list each with brief description)
          - âš ï¸ Comments not addressed (explain why)
          - ðŸ§ª Test results
          - ðŸ“ Additional notes

          # IMPORTANT GUIDELINES

          - Be surgical - only change what's needed to address feedback
          - If CodeRabbit is wrong, explain why in your response
          - Always run tests after changes
          - Don't blindly accept every suggestion - use judgment
          - If you can't address a comment, explain why clearly

          # AVOIDING LOOPS

          - Make ONE round of changes per CodeRabbit review
          - Don't re-trigger CodeRabbit by mentioning it or requesting re-review
          - Focus on fixing issues, not perfecting code

          PROMPT_END
          EOF

      - name: Setup GitHub MCP Server
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          {
            "mcpServers": {
              "repository-summary": {
                "type": "http",
                "url": "https://agents-md-generator.fastmcp.app/mcp"
              },
              "code-search": {
                "type": "http",
                "url": "https://public-code-search.fastmcp.app/mcp"
              },
              "github-research": {
                "type": "stdio",
                "command": "uvx",
                "args": ["github-research-mcp"],
                "env": {
                  "DISABLE_SUMMARIES": "true",
                  "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                }
              }
            }
          }
          EOF

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1.0.23
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
          prompt: ${{ steps.prompt.outputs.PROMPT }}
          track_progress: true
          claude_args: |
            --allowed-tools mcp__repository-summary,mcp__code-search,mcp__github-research,Bash(make:*,git:add:*,git:commit:*,git:push:*,git:status:*,git:diff:*,gh:api:*)
            --mcp-config /tmp/mcp-config/mcp-servers.json
