name: Claude Issue Creator

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  prepare:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude-issue')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude-issue')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude-issue')) ||
      (github.event_name == 'pull_request' && contains(github.event.pull_request.title, '@claude-issue'))
    runs-on: ubuntu-latest
    outputs:
      prompt: ${{ steps.build-prompt.outputs.PROMPT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build prompt with shared clauses
        id: build-prompt
        run: |
          # Build prompt from shared fragments
          {
            echo 'PROMPT<<PROMPT_END'
            cat github/prompts/project-intro.md
            echo ""
            cat github/prompts/getting-started.md | sed \
              -e "s|ISSUE_OR_PR|${{ github.event_name == 'issues' && 'issue' || 'pull request' }}|g" \
              -e "s|ISSUE_NUMBER|${{ github.event.issue.number || github.event.pull_request.number }}|g" \
              -e "s|REPO_NAME|${{ github.repository }}|g"
            echo ""
            cat github/prompts/create-issues.md
            echo ""
            cat github/prompts/resolve-threads.md
            echo ""
            echo 'PROMPT_END'
          } >> $GITHUB_OUTPUT

  claude:
    needs: prepare
    uses: ./.github/workflows/run-claude.yml
    with:
      python-version: '3.10'
      fetch-depth: 1
      prompt: ${{ needs.prepare.outputs.prompt }}
      allowed-tools: mcp__repository-summary,mcp__code-search,mcp__github-research,WebSearch,WebFetch,Bash(make:*,gh:api:*,gh:issue:*)
    secrets:
      claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
