name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'src/**'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: '3.12'
          fetch-depth: 0

      - name: Install documentation dependencies
        run: |
          uv sync --group docs

      - name: Configure Git for deployment
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Build and deploy documentation
        run: |
          uv run --group docs mkdocs gh-deploy --force
