name: Run Claude Code Action

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to install'
        required: false
        type: string
        default: '3.10'
      checkout-ref:
        description: 'Git ref to checkout'
        required: false
        type: string
        default: ''
      fetch-depth:
        description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
        required: false
        type: number
        default: 1
      prompt:
        description: 'Prompt to pass to Claude'
        required: true
        type: string
      allowed-tools:
        description: 'Comma-separated list of allowed tools for Claude'
        required: true
        type: string
      claude-args:
        description: 'Additional arguments to pass to Claude'
        required: false
        type: string
        default: ''
      track-progress:
        description: 'Whether Claude should track progress'
        required: false
        type: boolean
        default: true
      mcp-config:
        description: 'MCP server configuration JSON'
        required: false
        type: string
        default: |
          {
            "mcpServers": {
              "repository-summary": {
                "type": "http",
                "url": "https://agents-md-generator.fastmcp.app/mcp"
              },
              "code-search": {
                "type": "http",
                "url": "https://public-code-search.fastmcp.app/mcp"
              },
              "github-research": {
                "type": "stdio",
                "command": "uvx",
                "args": [
                  "github-research-mcp"
                ],
                "env": {
                  "DISABLE_SUMMARIES": "true",
                  "GITHUB_PERSONAL_ACCESS_TOKEN": "${{ secrets.GITHUB_TOKEN }}"
                }
              }
            }
          }
    secrets:
      claude-oauth-token:
        description: 'Claude OAuth token'
        required: true

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Setup MCP Server
        run: |
          mkdir -p /tmp/mcp-config
          cat > /tmp/mcp-config/mcp-servers.json << 'EOF'
          ${{ inputs.mcp-config }}
          EOF

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1.0.23
        with:
          claude_code_oauth_token: ${{ secrets.claude-oauth-token }}
          prompt: ${{ inputs.prompt }}
          track_progress: ${{ inputs.track-progress }}
          claude_args: |
            --allowed-tools ${{ inputs.allowed-tools }}
            --mcp-config /tmp/mcp-config/mcp-servers.json
            ${{ inputs.claude-args }}
