name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ matrix.python-version }}
        install-dependencies: 'true'

    - name: Run pytest
      run: |
        uv run pytest -v

    - name: Run smoke tests
      run: |
        uv run kb-dashboard --help

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: '3.12'
        install-dependencies: 'true'

    - name: Run linting
      run: |
        uv run ruff check . --fix
        uv run ruff format . --check

  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python Environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: '3.12'
        install-dependencies: 'true'

    - name: Run type checking
      run: |
        uv run basedpyright
