# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from enum import Enum
from typing import Annotated, Literal

from pydantic import Field, field_validator

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone, RootDict

KBN_DEFAULT_CONTROL_WIDTH = 'medium'
KBN_DEFAULT_SEARCH_TECHNIQUE = 'prefix'


class KbnControlSort(BaseRawVwModel):
    """Sorting configuration for options in a control."""

    by: str | None = Field(default=None)
    'The field by which to sort the options.'
    direction: Literal['asc', 'desc'] | None = Field(default=None)
    "The direction of the sort, either 'asc' or 'desc'."


class KbnBaseControlExplicitInput(BaseRawVwModel):
    """Base class for the `explicitInput` part of Kbn controls."""

    id: str | None = Field(default=None)
    'The unique identifier for the control.'


class SearchTechnique(str, Enum):
    """Enumeration for Search techniques used in options list controls."""

    PREFIX = 'prefix'
    'Search technique that filters options starting with the input text.'
    WILDCARD = 'wildcard'
    'Search technique that filters options containing the input text.'
    EXACT = 'exact'
    'Search technique that filters options matching the input text exactly.'


class KbnOptionsListControlExplicitInput(KbnBaseControlExplicitInput):
    """Explicit input for options list controls."""

    dataViewId: str | None = Field(default=None)
    'The ID of the data view (index pattern) the control operates on.'
    fieldName: str | None = Field(default=None)
    'The name of the field within the data view that the control is associated with.'
    title: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'The label for the control.'
    searchTechnique: SearchTechnique | None = Field(default=None)
    'The search technique used for filtering options.'
    selectedOptions: Annotated[list[str], OmitIfNone()] | None = Field(default=None)
    'A list of options that are preselected when the control is initialized.'
    singleSelect: Annotated[bool | None, OmitIfNone()] | None = Field(default=None)
    sort: KbnControlSort | None = Field(default=None)
    'Sorting configuration for the options in the control.'
    runPastTimeout: Annotated[bool | None, OmitIfNone()] | None = Field(default=None)
    'If set to true, delay the display of the list of values until the results are fully loaded.'


class KbnRangeSliderControlExplicitInput(KbnBaseControlExplicitInput):
    """Explicit input for range slider controls."""

    dataViewId: str | None = Field(default=None)
    'The ID of the data view (index pattern) the control operates on.'
    fieldName: str | None = Field(default=None)
    'The name of the field within the data view that the control is associated with.'
    title: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'The label for the control.'
    step: int | float | None = Field(default=None)
    'The step size for the range slider, if applicable. If not set, defaults to 1.'


class KbnBaseControl(BaseRawVwModel):
    """Base class for Kibana controls."""

    grow: bool | None = Field(default=None)
    'If true, the control will expand to fill available space.'
    order: int | None = Field(default=None)
    'The order of the control in the dashboard layout.'
    width: Literal['small', 'medium', 'large'] | None = Field(default=None)
    "The width of the control in the dashboard layout, e.g., 'small', 'medium', 'large'."


class KbnRangeSliderControl(KbnBaseControl):
    """Range slider control for a Kibana Dashboard."""

    type: Literal['rangeSliderControl'] = Field(default='rangeSliderControl')
    explicitInput: KbnRangeSliderControlExplicitInput | None = Field(default=None)
    'The actual definition of the slider control.'


class KbnOptionsListControl(KbnBaseControl):
    """Options list control for a Kibana Dashboard."""

    type: Literal['optionsListControl'] = Field(default='optionsListControl')
    explicitInput: KbnOptionsListControlExplicitInput | None = None
    'The actual definition of the options list control.'


class KbnTimeSliderControlExplicitInput(KbnBaseControlExplicitInput):
    """Explicit input for time slider controls."""

    timesliceStartAsPercentageOfTimeRange: float | None = Field(default=None)
    'The start of the timeslice as a percentage of the total time range.'
    timesliceEndAsPercentageOfTimeRange: float | None = Field(default=None)
    'The end of the timeslice as a percentage of the total time range.'


class KbnTimeSliderControl(KbnBaseControl):
    """Time slider control for a Kibana Dashboard."""

    type: Literal['timeSlider'] = Field(default='timeSlider')
    explicitInput: KbnTimeSliderControlExplicitInput | None = Field(default=None)
    'The actual definition of the time slider control.'


class KbnESQLControlExplicitInput(KbnBaseControlExplicitInput):
    """Explicit input for ES|QL controls."""

    variableName: str | None = Field(default=None)
    'The name of the ES|QL variable.'
    variableType: str | None = Field(default=None)
    "The type of variable ('time_literal', 'fields', 'values', 'multi_values', 'functions')."
    esqlQuery: str | None = Field(default=None)
    'The ES|QL query string.'
    controlType: str | None = Field(default=None)
    "The control type ('STATIC_VALUES' or 'VALUES_FROM_QUERY')."
    title: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Display title for the control.'
    selectedOptions: list[str] = Field(default_factory=list)
    'Currently selected options.'
    singleSelect: Annotated[bool | None, OmitIfNone()] = Field(default=None)
    'Whether to allow only single selection.'
    availableOptions: Annotated[list[str] | None, OmitIfNone()] = Field(default=None)
    'For STATIC_VALUES controls, the list of available options.'


class KbnESQLControl(KbnBaseControl):
    """ES|QL control for a Kibana Dashboard."""

    type: Literal['esqlControl'] = Field(default='esqlControl')
    explicitInput: KbnESQLControlExplicitInput | None = Field(default=None)
    'The actual definition of the ES|QL control.'


class KbnIgnoreParentSettingsJson(BaseRawVwModel):
    """Settings that control whether to ignore inherited values from the dashboard."""

    ignoreFilters: bool | None = Field(default=None)
    ignoreQuery: bool | None = Field(default=None)
    ignoreTimerange: bool | None = Field(default=None)
    ignoreValidations: bool | None = Field(default=None)


type KbnControlTypes = KbnRangeSliderControl | KbnOptionsListControl | KbnTimeSliderControl | KbnESQLControl


class KbnControlPanelsJson(RootDict[KbnControlTypes]):
    """A dictionary mapping control IDs to their respective control configurations."""


class ControlStyleEnum(str, Enum):
    """Enumeration for control styles in Kibana dashboards."""

    ONE_LINE = 'oneLine'
    'Control style where controls are displayed in a single line.'
    TWO_LINE = 'twoLine'
    'Control style where controls are displayed in two lines.'


class ChainingSystemEnum(str, Enum):
    """Enumeration for chaining systems in Kibana dashboards."""

    HIERARCHICAL = 'HIERARCHICAL'
    'Chaining system where controls filter the values of other controls.'
    NONE = 'NONE'
    'No chaining system applied to the controls.'


class KbnControlGroupInput(BaseRawVwModel):
    """Definition for the Controls part of a Kibana Dashboard."""

    chainingSystem: ChainingSystemEnum | None = Field(default=None)
    "The chaining system applied to the controls, e.g., 'HIERARCHICAL' or 'NONE'."
    controlStyle: ControlStyleEnum | None = Field(default=None)
    "The style of the controls, e.g., 'oneLine' or 'twoLine'."
    ignoreParentSettingsJSON: KbnIgnoreParentSettingsJson | None = None
    panelsJSON: KbnControlPanelsJson | None = None
    showApplySelections: bool | None = None

    @field_validator('ignoreParentSettingsJSON', mode='before')
    @classmethod
    def _parse_ignoreParentSettingsJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json
            from typing import cast as _cast

            return _cast('object', _json.loads(v))
        return v

    @field_validator('panelsJSON', mode='before')
    @classmethod
    def _parse_panelsJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json
            from typing import cast as _cast

            return _cast('object', _json.loads(v))
        return v
