# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models for parsing real-world Kibana dashboard JSON."""

from kb_dashboard_tools.decompile.kbn_raw_models.dashboard.view import KbnDashboard

__all__ = ['KbnDashboard']
