# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""KbnRaw* permissive view models for parsing real-world Kibana dashboard JSON."""

from kb_dashboard_tools.decompile.kbn_raw_models.dashboard.view import KbnRawDashboard

__all__ = ['KbnRawDashboard']
