# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Annotated, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.charts.base.view import KbnRawLegendSize, KbnRawRangePalette
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone


class KbnRawHeatmapGridConfig(BaseRawVwModel):
    """View model for heatmap grid configuration.

    Controls visibility of cell labels, axis labels, and axis titles in the heatmap.
    """

    type: Literal['heatmap_grid'] = 'heatmap_grid'
    """Type identifier for heatmap grid configuration."""

    isCellLabelVisible: bool = Field(default=False)
    """Whether to show labels inside heatmap cells. Defaults to false."""

    isXAxisLabelVisible: bool = Field(default=True)
    """Whether to show X-axis labels. Defaults to true."""

    isXAxisTitleVisible: bool = Field(default=True)
    """Whether to show X-axis title. Defaults to true."""

    isYAxisLabelVisible: bool = Field(default=True)
    """Whether to show Y-axis labels. Defaults to true."""

    isYAxisTitleVisible: bool = Field(default=True)
    """Whether to show Y-axis title. Defaults to true."""


class KbnRawHeatmapLegendConfig(BaseRawVwModel):
    """View model for heatmap legend configuration.

    Controls visibility and position of the color legend.
    """

    type: Literal['heatmap_legend'] = 'heatmap_legend'
    """Type identifier for heatmap legend configuration."""

    isVisible: bool = Field(default=True)
    """Whether to show the legend. Defaults to true."""

    position: Literal['top', 'right', 'bottom', 'left'] = Field(default='right')
    """Position of the legend relative to the chart. Defaults to 'right'."""


class KbnRawHeatmapVisualizationState(BaseRawVwModel):
    """View model for heatmap visualization state after compilation to Kibana Lens format.

    This model represents the complete visualization state for heatmap visualizations as stored
    in the Kibana saved object JSON structure. Heatmap visualizations display data as a matrix
    where cell colors represent metric values, typically used for visualizing patterns across
    two categorical dimensions.

    Unlike multi-layer chart types (pie, XY), heatmap visualizations use a flat structure where
    layer properties are directly on the visualization state object, not nested in a layers array.

    The visualization state is part of the larger Lens panel configuration and defines how
    the heatmap should be rendered in Kibana dashboards.

    See Also:
        Kibana type definition: `HeatmapVisualizationState` in Kibana source code.
    """

    layerId: str | None = Field(default=None)
    """Unique identifier for the layer within the visualization."""

    layerType: Literal['data'] = 'data'
    """Always 'data' for heatmap visualizations."""

    shape: Literal['heatmap'] = 'heatmap'
    """Always 'heatmap' for heatmap visualizations."""

    xAccessor: str | None = Field(default=None)
    """Field accessor ID for the X-axis dimension."""

    yAccessor: Annotated[str | None, OmitIfNone()] = Field(default=None)
    """Field accessor ID for the Y-axis dimension. Optional for 1D heatmaps."""

    valueAccessor: str | None = Field(default=None)
    """Field accessor ID for the metric that determines cell color intensity."""

    gridConfig: KbnRawHeatmapGridConfig = Field(default_factory=KbnRawHeatmapGridConfig)
    """Grid configuration controlling cell and axis label visibility. Always present with defaults."""

    legend: KbnRawHeatmapLegendConfig = Field(default_factory=KbnRawHeatmapLegendConfig)
    """Legend configuration controlling visibility and position. Always present with defaults."""

    legendSize: Annotated[KbnRawLegendSize | None, OmitIfNone()] = Field(default=None)
    """Optional legend size."""

    palette: Annotated[KbnRawRangePalette | None, OmitIfNone()] = Field(default=None)
    """Optional range-based palette settings for heatmap color stops."""
