# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Annotated, Any

from pydantic import Field, field_validator

from kb_dashboard_tools.decompile.kbn_raw_models.controls.view import KbnControlGroupInput
from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnSavedObjectMeta
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, KbnReference, OmitIfNone


class KbnDashboardOptions(BaseRawVwModel):
    """Represents the global options for a Kibana dashboard."""

    useMargins: bool | None = None
    'Whether to put space between panels in the dashboard.'
    syncColors: bool | None = None
    'Applies the same color palette to all panels on the dashboard.'
    syncCursor: bool | None = None
    'When you hover your cursor over a time series chart or a heatmap, the cursor on all other related dashboard charts appears.'
    syncTooltips: bool | None = None
    'When you hover your cursor over a Lens chart, the tooltips on all other related dashboard charts automatically appear.'
    hidePanelTitles: bool | None = None
    'Whether to hide the titles in the panel headers.'


class KbnDashboardSectionGridData(BaseRawVwModel):
    """Grid metadata for a collapsible dashboard section header."""

    y: int | None = None
    i: str | None = None


class KbnDashboardSection(BaseRawVwModel):
    """Represents a collapsible dashboard section in Kibana saved object attributes."""

    title: str | None = None
    collapsed: Annotated[bool | None, OmitIfNone()] = None
    gridData: KbnDashboardSectionGridData | None = None


class KbnDashboardAttributes(BaseRawVwModel):
    title: str | None = None
    description: str | None = None
    panelsJSON: list[Any] | None = None
    sections: Annotated[list[KbnDashboardSection] | None, OmitIfNone()] = Field(default=None)
    optionsJSON: KbnDashboardOptions | None = None
    kibanaSavedObjectMeta: KbnSavedObjectMeta | None = None
    timeRestore: bool | None = None
    timeFrom: Annotated[str | None, OmitIfNone()] = Field(default=None)
    timeTo: Annotated[str | None, OmitIfNone()] = Field(default=None)
    version: int | None = None
    controlGroupInput: KbnControlGroupInput | None = None

    @field_validator('panelsJSON', mode='before')
    @classmethod
    def _parse_panelsJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json
            from typing import cast as _cast

            return _cast('object', _json.loads(v))
        return v

    @field_validator('optionsJSON', mode='before')
    @classmethod
    def _parse_optionsJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json
            from typing import cast as _cast

            return _cast('object', _json.loads(v))
        return v


class KbnDashboard(BaseRawVwModel):
    """Represents the top-level Kibana dashboard JSON structure."""

    attributes: KbnDashboardAttributes | None = None
    coreMigrationVersion: str | None = None
    created_at: str | None = None
    created_by: str | None = None
    id: str | None = None
    managed: bool | None = None
    references: list[KbnReference] = Field(default_factory=list)
    type: str | None = None
    typeMigrationVersion: str | None = None
    updated_at: str | None = None
    updated_by: str | None = None
    version: str | None = None
