# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnQuery(BaseRawVwModel):
    """Represents the query object within state.query in the Kibana JSON structure."""

    query: str | None = None
    language: str | None = None


class KbnESQLQuery(BaseRawVwModel):
    """Represents the query object within state.query in the Kibana JSON structure."""

    esql: str | None = None
