# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Literal

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnRawQuery(BaseRawVwModel):
    """Represents the query object within state.query in the Kibana JSON structure."""

    query: str | None = None
    language: Literal['kuery', 'lucene'] | None = None


class KbnRawESQLQuery(BaseRawVwModel):
    """Represents the query object within state.query in the Kibana JSON structure."""

    esql: str | None = None
