# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnBasePanel, KbnBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnUrlImageInfoSrc(BaseRawVwModel):
    type: Literal['url'] = 'url'
    url: str | None = None


class KbnUrlImageSizing(BaseRawVwModel):
    objectFit: Literal['contain', 'cover', 'fill', 'none'] | None = None


class KbnImageConfig(BaseRawVwModel):
    src: KbnUrlImageInfoSrc | None = Field(default=None)
    altText: str | None = Field(default=None)
    backgroundColor: str | None = Field(default=None)
    sizing: KbnUrlImageSizing | None = Field(default=None)


class KbnImageEmbeddableConfig(KbnBasePanelEmbeddableConfig):
    imageConfig: KbnImageConfig | None = Field(default=None)


class KbnImagePanel(KbnBasePanel):
    """Represents an image panel in the Kibana Kbn structure."""

    type: Literal['image'] = 'image'
    embeddableConfig: KbnImageEmbeddableConfig | None = None
