# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnRawBasePanel, KbnRawBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnRawUrlImageInfoSrc(BaseRawVwModel):
    type: Literal['url'] = 'url'
    url: str | None = None


class KbnRawUrlImageSizing(BaseRawVwModel):
    objectFit: Literal['contain', 'cover', 'fill', 'none'] | None = None


class KbnRawImageConfig(BaseRawVwModel):
    src: KbnRawUrlImageInfoSrc | None = Field(default=None)
    altText: str | None = Field(default=None)
    backgroundColor: str | None = Field(default=None)
    sizing: KbnRawUrlImageSizing | None = Field(default=None)


class KbnRawImageEmbeddableConfig(KbnRawBasePanelEmbeddableConfig):
    imageConfig: KbnRawImageConfig | None = Field(default=None)


class KbnRawImagePanel(KbnRawBasePanel):
    """Represents an image panel in the Kibana Kbn structure."""

    type: Literal['image'] = 'image'
    embeddableConfig: KbnRawImageEmbeddableConfig | None = None
