# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from enum import StrEnum
from typing import TYPE_CHECKING, Annotated, Any, Literal

from pydantic import Field, RootModel

from kb_dashboard_tools.decompile.kbn_raw_models.filters.view import KbnRawFilter
from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnRawBasePanel, KbnRawBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnRawESQLQuery, KbnRawQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, KbnRawReference, OmitIfNone

if TYPE_CHECKING:
    from .datatable.view import KbnRawDatatableVisualizationState
    from .gauge.view import KbnRawGaugeVisualizationState
    from .heatmap.view import KbnRawHeatmapVisualizationState
    from .metric.view import KbnRawESQLMetricVisualizationState, KbnRawMetricVisualizationState
    from .mosaic.view import KbnRawMosaicVisualizationState
    from .pie.view import KbnRawPieVisualizationState
    from .tagcloud.view import KbnRawTagcloudVisualizationState
    from .waffle.view import KbnRawWaffleVisualizationState
    from .xy.view import KbnRawXYVisualizationState

    KbnVisualizationStateTypes = (
        KbnRawPieVisualizationState
        | KbnRawMetricVisualizationState
        | KbnRawESQLMetricVisualizationState
        | KbnRawGaugeVisualizationState
        | KbnRawHeatmapVisualizationState
        | KbnRawXYVisualizationState
        | KbnRawDatatableVisualizationState
        | KbnRawTagcloudVisualizationState
        | KbnRawMosaicVisualizationState
        | KbnRawWaffleVisualizationState
    )


class KbnRawFormBasedDataSourceStateLayer(BaseRawVwModel):
    """Represents the datasource state for a single layer within a Lens panel in the Kibana JSON structure."""

    columns: dict[str, Any] = Field(default_factory=dict)
    columnOrder: list[str] = Field(default_factory=list)
    incompleteColumns: dict[str, Any] = Field(default_factory=dict)
    sampling: int | None = None
    indexPatternId: Annotated[str | None, OmitIfNone()] = None
    linkToLayers: Annotated[list[str] | None, OmitIfNone()] = None
    ignoreGlobalFilters: Annotated[bool | None, OmitIfNone()] = None


class KbnRawFormBasedDataSourceStateLayerById(RootModel[dict[str, KbnRawFormBasedDataSourceStateLayer]]):
    """Represents a mapping of layer IDs to their corresponding KbnLayerDataSourceState objects."""

    root: dict[str, KbnRawFormBasedDataSourceStateLayer] = Field(default_factory=dict)


class KbnRawFormBasedDataSourceState(BaseRawVwModel):
    """Represents the datasource state for a Lens panel in the Kibana JSON structure."""

    layers: KbnRawFormBasedDataSourceStateLayerById = Field(default_factory=KbnRawFormBasedDataSourceStateLayerById)
    currentIndexPatternId: Annotated[str | None, OmitIfNone()] = None


class KbnRawTextBasedDataSourceStateLayer(BaseRawVwModel):
    query: KbnRawESQLQuery | None = None
    columns: list[Any] | None = None
    allColumns: list[Any] | None = None
    timeField: str | None = None


class KbnRawTextBasedDataSourceStateLayerById(RootModel[dict[str, KbnRawTextBasedDataSourceStateLayer]]):
    root: dict[str, KbnRawTextBasedDataSourceStateLayer] = Field(default_factory=dict)


class KbnRawTextBasedDataSourceState(BaseRawVwModel):
    layers: KbnRawTextBasedDataSourceStateLayerById | None = Field(default=None)


class KbnRawIndexPatternBasedDataSourceStateById(RootModel[dict[str, str]]):
    root: dict[str, str] = Field(default_factory=dict)


class KbnRawIndexPatternBasedDataSourceState(BaseRawVwModel):
    """Index Pattern based datasource is not yet implemented."""

    layers: KbnRawIndexPatternBasedDataSourceStateById = Field(default_factory=KbnRawIndexPatternBasedDataSourceStateById)


class KbnRawDataSourceState(BaseRawVwModel):
    """Represents the overall datasource states for a Lens panel in the Kibana JSON structure."""

    formBased: Annotated[KbnRawFormBasedDataSourceState | None, OmitIfNone()] = None
    """Form-based datasource state. Only included for Lens panels using data views."""

    indexpattern: Annotated[KbnRawIndexPatternBasedDataSourceState | None, OmitIfNone()] = None
    """Index pattern datasource state (not implemented, rarely used)."""

    textBased: Annotated[KbnRawTextBasedDataSourceState | None, OmitIfNone()] = None
    """Text-based (ES|QL) datasource state. Only included for ES|QL panels."""


class KbnRawVisualizationTypeEnum(StrEnum):
    XY = 'lnsXY'
    PIE = 'lnsPie'
    METRIC = 'lnsMetric'
    GAUGE = 'lnsGauge'
    HEATMAP = 'lnsHeatmap'
    DATATABLE = 'lnsDatatable'
    TAGCLOUD = 'lnsTagcloud'


class KbnRawLensPanelState(BaseRawVwModel):
    """Represents the 'state' object within a Lens panel in the Kibana JSON structure."""

    visualization: Any  # KbnRawPieVisualizationState | KbnRawMetricVisualizationState | KbnRawXYVisualizationState | KbnRawTagcloudVisualizationState | None = None
    query: KbnRawQuery | KbnRawESQLQuery | None = Field(default=None)
    filters: list[KbnRawFilter] | None = Field(default=None)
    datasourceStates: KbnRawDataSourceState | None = Field(default=None)
    internalReferences: list[Any] | None = Field(default=None)
    adHocDataViews: dict[str, Any] | None = Field(default=None)


class KbnRawLensPanelAttributes(BaseRawVwModel):
    title: str = ''
    visualizationType: KbnRawVisualizationTypeEnum | None = None
    type: Literal['lens'] = 'lens'
    references: list[KbnRawReference] | None = Field(default=None)
    state: KbnRawLensPanelState | None = None


class KbnRawLensPanelEmbeddableConfig(KbnRawBasePanelEmbeddableConfig):
    attributes: KbnRawLensPanelAttributes | None = None

    syncTooltips: bool = Field(
        default=False,
        description='(Optional) Whether to sync tooltips across visualizations. Defaults to False.',
    )

    syncColors: bool = Field(
        default=False,
        description='(Optional) Whether to sync colors across visualizations. Defaults to False.',
    )

    syncCursor: bool = Field(
        default=True,
        description='(Optional) Whether to sync cursor across visualizations. Defaults to True.',
    )

    filters: list[Any] = Field(
        default_factory=list,
        description='(Optional) List of filters applied to the Lens visualization. Defaults to empty list.',
    )

    query: KbnRawQuery | None = Field(
        default=None,
        description="(Optional) Query object for the Lens visualization. Defaults to empty query with 'kuery' language.",
    )


class KbnRawLensPanel(KbnRawBasePanel):
    type: Literal['lens'] = 'lens'
    embeddableConfig: KbnRawLensPanelEmbeddableConfig | None = None
