# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from enum import StrEnum
from typing import TYPE_CHECKING, Annotated, Any, Literal

from pydantic import Field, RootModel

from kb_dashboard_tools.decompile.kbn_raw_models.filters.view import KbnFilter
from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnBasePanel, KbnBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnESQLQuery, KbnQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, KbnReference, OmitIfNone

if TYPE_CHECKING:
    from .datatable.view import KbnDatatableVisualizationState
    from .gauge.view import KbnGaugeVisualizationState
    from .heatmap.view import KbnHeatmapVisualizationState
    from .metric.view import KbnESQLMetricVisualizationState, KbnMetricVisualizationState
    from .mosaic.view import KbnMosaicVisualizationState
    from .pie.view import KbnPieVisualizationState
    from .tagcloud.view import KbnTagcloudVisualizationState
    from .waffle.view import KbnWaffleVisualizationState
    from .xy.view import KbnXYVisualizationState

    KbnVisualizationStateTypes = (
        KbnPieVisualizationState
        | KbnMetricVisualizationState
        | KbnESQLMetricVisualizationState
        | KbnGaugeVisualizationState
        | KbnHeatmapVisualizationState
        | KbnXYVisualizationState
        | KbnDatatableVisualizationState
        | KbnTagcloudVisualizationState
        | KbnMosaicVisualizationState
        | KbnWaffleVisualizationState
    )


class KbnFormBasedDataSourceStateLayer(BaseRawVwModel):
    """Represents the datasource state for a single layer within a Lens panel in the Kibana JSON structure."""

    columns: dict[str, Any] = Field(default_factory=dict)
    columnOrder: list[str] = Field(default_factory=list)
    incompleteColumns: dict[str, Any] = Field(default_factory=dict)
    sampling: int | None = None
    indexPatternId: Annotated[str | None, OmitIfNone()] = None
    linkToLayers: Annotated[list[str] | None, OmitIfNone()] = None
    ignoreGlobalFilters: Annotated[bool | None, OmitIfNone()] = None


class KbnFormBasedDataSourceStateLayerById(RootModel[dict[str, KbnFormBasedDataSourceStateLayer]]):
    """Represents a mapping of layer IDs to their corresponding KbnLayerDataSourceState objects."""

    root: dict[str, KbnFormBasedDataSourceStateLayer] = Field(default_factory=dict)


class KbnFormBasedDataSourceState(BaseRawVwModel):
    """Represents the datasource state for a Lens panel in the Kibana JSON structure."""

    layers: KbnFormBasedDataSourceStateLayerById = Field(default_factory=KbnFormBasedDataSourceStateLayerById)
    currentIndexPatternId: Annotated[str | None, OmitIfNone()] = None


class KbnTextBasedDataSourceStateLayer(BaseRawVwModel):
    query: KbnESQLQuery | None = None
    columns: list[Any] | None = None
    allColumns: list[Any] | None = None
    timeField: str | None = None


class KbnTextBasedDataSourceStateLayerById(RootModel[dict[str, KbnTextBasedDataSourceStateLayer]]):
    root: dict[str, KbnTextBasedDataSourceStateLayer] = Field(default_factory=dict)


class KbnTextBasedDataSourceState(BaseRawVwModel):
    layers: KbnTextBasedDataSourceStateLayerById | None = Field(default=None)


class KbnIndexPatternBasedDataSourceStateById(RootModel[dict[str, str]]):
    root: dict[str, str] = Field(default_factory=dict)


class KbnIndexPatternBasedDataSourceState(BaseRawVwModel):
    """Index Pattern based datasource is not yet implemented."""

    layers: KbnIndexPatternBasedDataSourceStateById = Field(default_factory=KbnIndexPatternBasedDataSourceStateById)


class KbnDataSourceState(BaseRawVwModel):
    """Represents the overall datasource states for a Lens panel in the Kibana JSON structure."""

    formBased: Annotated[KbnFormBasedDataSourceState | None, OmitIfNone()] = None
    'Form-based datasource state. Only included for Lens panels using data views.'
    indexpattern: Annotated[KbnIndexPatternBasedDataSourceState | None, OmitIfNone()] = None
    'Index pattern datasource state (not implemented, rarely used).'
    textBased: Annotated[KbnTextBasedDataSourceState | None, OmitIfNone()] = None
    'Text-based (ES|QL) datasource state. Only included for ES|QL panels.'


class KbnVisualizationTypeEnum(StrEnum):
    XY = 'lnsXY'
    PIE = 'lnsPie'
    METRIC = 'lnsMetric'
    GAUGE = 'lnsGauge'
    HEATMAP = 'lnsHeatmap'
    DATATABLE = 'lnsDatatable'
    TAGCLOUD = 'lnsTagcloud'
    MOSAIC = 'lnsMosaic'
    WAFFLE = 'lnsWaffle'


class KbnLensPanelState(BaseRawVwModel):
    """Represents the 'state' object within a Lens panel in the Kibana JSON structure."""

    visualization: Any | None = None
    query: KbnQuery | KbnESQLQuery | None = Field(default=None)
    filters: list[KbnFilter] | None = Field(default=None)
    datasourceStates: KbnDataSourceState | None = Field(default=None)
    internalReferences: list[Any] | None = Field(default=None)
    adHocDataViews: dict[str, Any] | None = Field(default=None)


class KbnLensPanelAttributes(BaseRawVwModel):
    title: str = ''
    visualizationType: KbnVisualizationTypeEnum | None = None
    type: Literal['lens'] = 'lens'
    references: list[KbnReference] | None = Field(default=None)
    state: KbnLensPanelState | None = None


class KbnLensPanelEmbeddableConfig(KbnBasePanelEmbeddableConfig):
    attributes: KbnLensPanelAttributes | None = None
    syncTooltips: bool = Field(default=False, description='(Optional) Whether to sync tooltips across visualizations. Defaults to False.')
    syncColors: bool = Field(default=False, description='(Optional) Whether to sync colors across visualizations. Defaults to False.')
    syncCursor: bool = Field(default=True, description='(Optional) Whether to sync cursor across visualizations. Defaults to True.')
    filters: list[Any] = Field(
        default_factory=list, description='(Optional) List of filters applied to the Lens visualization. Defaults to empty list.'
    )
    query: KbnQuery | None = Field(
        default=None, description="(Optional) Query object for the Lens visualization. Defaults to empty query with 'kuery' language."
    )


class KbnLensPanel(KbnBasePanel):
    type: Literal['lens'] = 'lens'
    embeddableConfig: KbnLensPanelEmbeddableConfig | None = None
