# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from enum import StrEnum
from typing import Any

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnRawDrilldownTrigger(StrEnum):
    """Kibana drilldown trigger types."""

    VALUE_CLICK_TRIGGER = 'VALUE_CLICK_TRIGGER'
    FILTER_TRIGGER = 'FILTER_TRIGGER'
    SELECT_RANGE_TRIGGER = 'SELECT_RANGE_TRIGGER'


class KbnRawDashboardDrilldownConfig(BaseRawVwModel):
    """Configuration for dashboard-to-dashboard drilldown."""

    useCurrentFilters: bool = Field()
    """Whether to inherit current filters."""

    useCurrentDateRange: bool = Field()
    """Whether to inherit current time range."""


class KbnRawUrlDrilldownConfig(BaseRawVwModel):
    """Configuration for URL drilldown."""

    url: dict[str, str] = Field()
    """URL template payload."""

    openInNewTab: bool = Field()
    """Whether to open in a new tab."""

    encodeUrl: bool = Field(default=True)
    """Whether to URL-encode template variables."""


class KbnRawDrilldownAction(BaseRawVwModel):
    """Drilldown action configuration."""

    factoryId: str = Field()
    """Factory identifier for the drilldown type."""

    name: str = Field()
    """Display name for the drilldown."""

    config: dict[str, Any] = Field()
    """Configuration payload for the drilldown action."""


class KbnRawDrilldownEvent(BaseRawVwModel):
    """Drilldown event configuration."""

    eventId: str = Field()
    """Unique identifier for the drilldown event."""

    triggers: list[str] = Field()
    """List of trigger types that activate this drilldown."""

    action: KbnRawDrilldownAction = Field()
    """Action to perform when triggered."""


class KbnRawDynamicActions(BaseRawVwModel):
    """Dynamic actions configuration for enhancements."""

    events: list[KbnRawDrilldownEvent] = Field(default_factory=list)
    """List of drilldown events."""


class KbnRawEnhancements(BaseRawVwModel):
    """Enhancements configuration for panel embeddable config."""

    dynamicActions: KbnRawDynamicActions = Field(default_factory=KbnRawDynamicActions)
    """Dynamic actions configuration containing drilldown events."""
