# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from enum import StrEnum
from typing import Any

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel

DASHBOARD_TO_DASHBOARD_DRILLDOWN = 'DASHBOARD_TO_DASHBOARD_DRILLDOWN'
URL_DRILLDOWN = 'URL_DRILLDOWN'


class KbnDrilldownTrigger(StrEnum):
    """Kibana drilldown trigger types."""

    VALUE_CLICK_TRIGGER = 'VALUE_CLICK_TRIGGER'
    FILTER_TRIGGER = 'FILTER_TRIGGER'
    SELECT_RANGE_TRIGGER = 'SELECT_RANGE_TRIGGER'


class KbnDashboardDrilldownConfig(BaseRawVwModel):
    """Configuration for dashboard-to-dashboard drilldown."""

    useCurrentFilters: bool | None = Field(default=None)
    'Whether to inherit current filters.'
    useCurrentDateRange: bool | None = Field(default=None)
    'Whether to inherit current time range.'


class KbnUrlDrilldownConfig(BaseRawVwModel):
    """Configuration for URL drilldown."""

    url: dict[str, str] | None = Field(default=None)
    'URL template payload.'
    openInNewTab: bool | None = Field(default=None)
    'Whether to open in a new tab.'
    encodeUrl: bool = Field(default=True)
    'Whether to URL-encode template variables.'


class KbnDrilldownAction(BaseRawVwModel):
    """Drilldown action configuration."""

    factoryId: str | None = Field(default=None)
    'Factory identifier for the drilldown type.'
    name: str | None = Field(default=None)
    'Display name for the drilldown.'
    config: dict[str, Any] | None = Field(default=None)
    'Configuration payload for the drilldown action.'


class KbnDrilldownEvent(BaseRawVwModel):
    """Drilldown event configuration."""

    eventId: str | None = Field(default=None)
    'Unique identifier for the drilldown event.'
    triggers: list[str] | None = Field(default=None)
    'List of trigger types that activate this drilldown.'
    action: KbnDrilldownAction | None = Field(default=None)
    'Action to perform when triggered.'


class KbnDynamicActions(BaseRawVwModel):
    """Dynamic actions configuration for enhancements."""

    events: list[KbnDrilldownEvent] = Field(default_factory=list)
    'List of drilldown events.'


class KbnEnhancements(BaseRawVwModel):
    """Enhancements configuration for panel embeddable config."""

    dynamicActions: KbnDynamicActions = Field(default_factory=KbnDynamicActions)
    'Dynamic actions configuration containing drilldown events.'
