# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Annotated, Any

from pydantic import Field, field_validator

from kb_dashboard_tools.decompile.kbn_raw_models.filters.view import KbnRawFilter
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnRawQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone


class KbnRawGridData(BaseRawVwModel):
    """Represents the 'gridData' object in the Kibana JSON structure."""

    x: int | None = None
    y: int | None = None
    w: int | None = None
    h: int | None = None
    i: str | None = None
    sectionId: Annotated[str | None, OmitIfNone()] = None


class KbnRawBasePanelEmbeddableConfig(BaseRawVwModel):
    """Base model for embeddable configuration in Kibana panels."""

    title: Annotated[str | None, OmitIfNone()] = Field(default=None)
    enhancements: dict[str, Any] = Field(default_factory=dict)
    description: Annotated[str | None, OmitIfNone()] = Field(default=None)
    hidePanelTitles: Annotated[bool | None, OmitIfNone()] = None


class KbnRawBasePanel(BaseRawVwModel):
    """Base model for panel objects in the Kibana JSON structure."""

    panelIndex: str | None = None
    gridData: KbnRawGridData | None = None


class KbnRawSearchSourceJSON(BaseRawVwModel):
    """Represents the 'searchSourceJSON' object in the Kibana JSON structure."""

    filter: list[KbnRawFilter] | None = Field(default=None)
    query: KbnRawQuery | None = Field(default=None)


class KbnRawSavedObjectMeta(BaseRawVwModel):
    """Represents the 'kibanaSavedObjectMeta' object in the Kibana JSON structure."""

    searchSourceJSON: KbnRawSearchSourceJSON | None = Field(default=None)

    @field_validator('searchSourceJSON', mode='before')
    @classmethod
    def _parse_searchSourceJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json

            return _json.loads(v)  # pyright: ignore[reportAny]
        return v
