# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Annotated, Any

from pydantic import Field, field_validator

from kb_dashboard_tools.decompile.kbn_raw_models.filters.view import KbnFilter
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone

__all__ = ['KbnBasePanel', 'KbnBasePanelEmbeddableConfig', 'KbnGridData', 'KbnSavedObjectMeta', 'KbnSearchSourceJSON']


class KbnGridData(BaseRawVwModel):
    """Represents the 'gridData' object in the Kibana JSON structure."""

    x: int | None = None
    y: int | None = None
    w: int | None = None
    h: int | None = None
    i: str | None = None
    sectionId: Annotated[str | None, OmitIfNone()] = None


class KbnBasePanelEmbeddableConfig(BaseRawVwModel):
    """Base model for embeddable configuration in Kibana panels."""

    title: Annotated[str | None, OmitIfNone()] = Field(default=None)
    enhancements: dict[str, Any] = Field(default_factory=dict)
    description: Annotated[str | None, OmitIfNone()] = Field(default=None)
    hidePanelTitles: Annotated[bool | None, OmitIfNone()] = None


class KbnBasePanel(BaseRawVwModel):
    embeddableConfig: Any | None = None
    panelRefName: str | None = None
    description: str | None = None
    title: str | None = None
    type: str | None = None
    'Base model for panel objects in the Kibana JSON structure.'
    panelIndex: str | None = None
    gridData: KbnGridData | None = None


class KbnSearchSourceJSON(BaseRawVwModel):
    """Represents the 'searchSourceJSON' object in the Kibana JSON structure."""

    filter: list[KbnFilter] | None = Field(default=None)
    query: KbnQuery | None = Field(default=None)


class KbnSavedObjectMeta(BaseRawVwModel):
    """Represents the 'kibanaSavedObjectMeta' object in the Kibana JSON structure."""

    searchSourceJSON: KbnSearchSourceJSON | None = Field(default=None)

    @field_validator('searchSourceJSON', mode='before')
    @classmethod
    def _parse_searchSourceJSON_json(cls, v: object) -> object:
        if isinstance(v, str):
            import json as _json
            from typing import cast as _cast

            return _cast('object', _json.loads(v))
        return v
