# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Any, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnRawBasePanel, KbnRawBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnRawQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnRawVegaSavedVisDataSearchSource(BaseRawVwModel):
    query: KbnRawQuery | None = None
    filter: list[Any] | None = None


class KbnRawVegaSavedVisData(BaseRawVwModel):
    aggs: list[Any] | None = Field(default=None)
    searchSource: KbnRawVegaSavedVisDataSearchSource | None = None


class KbnRawVegaSavedVisParams(BaseRawVwModel):
    spec: str | None = None


class KbnRawVegaSavedVis(BaseRawVwModel):
    type: Literal['vega'] = 'vega'
    id: str | None = Field(default=None)
    title: str | None = Field(default=None)
    description: str | None = Field(default=None)
    params: KbnRawVegaSavedVisParams | None = Field(default=None)
    uiState: dict[str, Any] | None = Field(default=None)
    data: KbnRawVegaSavedVisData | None = Field(default=None)


class KbnRawVegaEmbeddableConfig(KbnRawBasePanelEmbeddableConfig):
    savedVis: KbnRawVegaSavedVis | None = None


class KbnRawVegaPanel(KbnRawBasePanel):
    """Represents a Vega panel in the Kibana Kbn structure."""

    type: Literal['visualization'] = 'visualization'
    embeddableConfig: KbnRawVegaEmbeddableConfig | None = None
