# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Any, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnBasePanel, KbnBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnVegaSavedVisDataSearchSource(BaseRawVwModel):
    query: KbnQuery | None = None
    filter: list[Any] | None = None


class KbnVegaSavedVisData(BaseRawVwModel):
    aggs: list[Any] | None = Field(default=None)
    searchSource: KbnVegaSavedVisDataSearchSource | None = None


class KbnVegaSavedVisParams(BaseRawVwModel):
    spec: str | None = None


class KbnVegaSavedVis(BaseRawVwModel):
    type: Literal['vega'] = 'vega'
    id: str | None = Field(default=None)
    title: str | None = Field(default=None)
    description: str | None = Field(default=None)
    params: KbnVegaSavedVisParams | None = Field(default=None)
    uiState: dict[str, Any] | None = Field(default=None)
    data: KbnVegaSavedVisData | None = Field(default=None)


class KbnVegaEmbeddableConfig(KbnBasePanelEmbeddableConfig):
    savedVis: KbnVegaSavedVis | None = None


class KbnVegaPanel(KbnBasePanel):
    """Represents a Vega panel in the Kibana Kbn structure."""

    type: Literal['visualization'] = 'visualization'
    embeddableConfig: KbnVegaEmbeddableConfig | None = None
