# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Annotated, Any

from pydantic import ConfigDict, Field

from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone

type FilterScalar = str | int | float | bool


class KbnBaseFilterMeta(BaseRawVwModel):
    disabled: bool | None = None
    'Indicates whether the filter is disabled.'
    negate: bool | None = None
    'Indicates whether the filter is negated (i.e., it filters out the specified values).'
    alias: str | None = None
    'An optional alias for the filter, used for display purposes.'
    index: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'The data view / index associated with the filter, if applicable.'


class KbnCombinedFilterMeta(KbnBaseFilterMeta):
    """Represents the meta information for a combined filter in the Kibana JSON structure."""

    type: str = Field(default='combined')
    relation: Annotated[str | None, OmitIfNone()] | None = None
    "The relation of the 'combined' filter, if applicable. Can be 'AND' or 'OR'."
    params: Annotated[list['KbnFilter'], 'KbnFilter', OmitIfNone()] | None = None
    'Parameters for the filter, which can include a list of other filters that are combined.'


class KbnFilterMeta(KbnBaseFilterMeta):
    """Represents the meta information of a filter in the Kibana JSON structure."""

    type: str | None = None
    "The type of filter, e.g., 'phrase', 'phrases', 'range', 'exists', etc."
    key: str | None = None
    'The key of the filter, typically the field name being filtered on.'
    field: str | None = None
    'The field name being filtered on, same as `key` in most cases.'
    params: Annotated[dict[str, Any] | list[FilterScalar] | None, OmitIfNone()] = Field(default=None)
    'Parameters for the filter, such as the value to match against.'


class KbnCustomFilterMeta(KbnBaseFilterMeta):
    """Represents the meta information for a custom filter in the Kibana JSON structure."""

    type: str = Field(default='custom')
    "The type of filter, which is 'custom' for custom filters."
    key: str = Field(default='query')
    "The key for the custom filter, which is always 'query'."


type KbnFilterMetaTypes = KbnFilterMeta | KbnCombinedFilterMeta | KbnCustomFilterMeta


class KbnFilterState(BaseRawVwModel):
    """Represents the $state of a filter."""

    store: str = Field(default='appState')


class KbnFilter(BaseRawVwModel):
    """Represents a filter object within state.filters in the Kibana JSON structure."""

    model_config: ConfigDict = ConfigDict(serialize_by_alias=True)
    'Configuration for the model to serialize using aliases for the $state field.'
    state: Annotated[KbnFilterState | None, OmitIfNone()] | None = Field(
        default=None, validation_alias='$state', serialization_alias='$state'
    )
    meta: KbnFilterMetaTypes | None = None
    query: Annotated[dict[str, Any] | None, OmitIfNone()] | None = None
    range: Annotated[dict[str, Any] | None, OmitIfNone()] = Field(default=None)
    'Raw ES range query, present on range-type filters alongside meta.'
