---
name: Claude Address CodeRabbit Feedback
on:
  pull_request_review:
    types:
      - submitted
concurrency:
  group: claude-coderabbit-${{ github.event.pull_request.number }}
  cancel-in-progress: false
permissions:
  contents: write
  pull-requests: write
  actions: read
  id-token: write
jobs:
  claude-coderabbit-response:
    if: |
      github.event.review.user.login == 'coderabbitai[bot]' &&
      (github.event.review.state == 'commented' || github.event.review.state == 'changes_requested') &&
      !github.event.pull_request.draft
    uses: ./.github/workflows/run-claude.yml
    with:
      checkout-ref: ${{ github.event.pull_request.head.ref }}
      allowed-bots: coderabbitai
      prompt: |
        You're a code assistant for kb-yaml-to-lens responding to CodeRabbit review feedback.

        # YOUR TASK
        CodeRabbit has left review feedback on PR  #${{ github.event.pull_request.number }}.
        Review ID: ${{ github.event.review.id }}
        Your goal is to:
        1. Check if another Claude workflow has already responded (if so, skip this run)
        2. Fetch all review comments from CodeRabbit for this PR
        3. Address each comment by making appropriate code changes
        4. Before completing, check again for newer reviews and address any new feedback
        5. Resolve review threads after fixing issues
        6. Run tests/linting to verify fixes
        7. Document what was fixed and what couldn't be fixed

        # GETTING STARTED

        ## STEP 1: Check for newer reviews
        Before doing any work, verify this is the most recent CodeRabbit review by calling:
        ```
        make gh-check-latest-review "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.number }}" "coderabbitai[bot]" "${{ github.event.review.id }}"
        ```
        If this command exits with non-zero status, a newer CodeRabbit review exists - skip this run as the newer review will be or is being processed.
        If it exits with zero status, this is the most recent CodeRabbit review, proceed with work.

        ## STEP 2: Fetch all review threads
        Fetch review threads using the make command:
        ```
        make gh-get-review-threads "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.number }}" "coderabbitai[bot]"
        ```
        This returns JSON with all unresolved review threads from CodeRabbit. Parse the JSON to get thread IDs, file paths, and comments.

        # ADDRESSING FEEDBACK
        For each unresolved CodeRabbit comment:
        1. Read the file and understand the context
        2. Make the suggested change (or a better alternative if you disagree)
        3. Document your reasoning if you deviate from the suggestion
        4. After all changes, run: `make lint` and `make test`
        5. Fix any failures caused by your changes

        # BEFORE COMPLETING: Check for additional feedback
        Before you finish and post your summary comment, check again for newer CodeRabbit reviews:
        ```
        make gh-check-latest-review "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.number }}" "coderabbitai[bot]" "${{ github.event.review.id }}"
        ```
        If this exits with non-zero status, a new CodeRabbit review arrived during your work:
        1. Get the latest review ID:
           ```
           make gh-get-latest-review "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.number }}" "coderabbitai[bot]"
           ```
           Parse the JSON output to extract the `.databaseId` field.
        2. Fetch the new review threads:
           ```
           make gh-get-review-threads "${{ github.repository_owner }}" "${{ github.event.repository.name }}" "${{ github.event.pull_request.number }}" "coderabbitai[bot]"
           ```
        3. Address the new feedback before posting your final summary.

        If no new feedback was found, proceed with posting your final summary.

        # RESOLVING THREADS
        After successfully addressing a comment, resolve the thread by calling:
        ```
        make gh-resolve-review-thread "THREAD_ID"
        ```
        Replace THREAD_ID with the actual thread ID from the review threads JSON.

        # REPORTING
        After all changes (including any new feedback found), comment on the PR with a summary:
        - ✅ Comments addressed (list each with brief description)
        - ⚠️ Comments not addressed (explain why)
        - 🧪 Test results
        - 📝 Additional notes
        - If new reviews arrived during this run, note: "✨ Also addressed feedback from newer CodeRabbit review (ID: $LATEST_REVIEW_ID)"

        # IMPORTANT GUIDELINES
        - Be surgical - only change what's needed to address feedback
        - If CodeRabbit is wrong, explain why in your response
        - Always run tests after changes
        - Don't blindly accept every suggestion - use judgment
        - If you can't address a comment, explain why clearly

        # AVOIDING LOOPS AND HANDLING CONCURRENT REVIEWS
        - Make ONE round of changes per workflow run (but capture all feedback including new reviews that arrive during your work)
        - Check for newer reviews at the start (skip if found) and before completing (address if found)
        - Don't re-trigger CodeRabbit by mentioning it or requesting re-review
        - Focus on fixing issues, not perfecting code
      allowed-tools: mcp__repository-summary,mcp__code-search,mcp__github-research,Bash(make:*,git:*,gh:api:*)
    secrets:
      claude-oauth-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
