---
name: Create GitHub Release
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG=$(git tag --sort=-v:refname | grep -v "$(git describe --tags)" | head -n 1)

          if [ -n "$PREV_TAG" ]; then
            echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
            git log ${PREV_TAG}..HEAD --pretty=format:"- %s (%h)" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "CHANGELOG=Initial release" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.CHANGELOG }}

            ## Installation

            **Python Package:**
            ```bash
            pip install dashboard-compiler==${{ steps.get_version.outputs.VERSION }}
            ```

            **Docker:**
            ```bash
            docker pull ghcr.io/strawgate/kb-yaml-to-lens/kb-dashboard-compiler:${{ steps.get_version.outputs.VERSION }}
            ```

            **Standalone Binaries:**
            Download platform-specific binaries from the assets below.

            **VS Code Extension:**
            Install from the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=strawgate.yaml-dashboard-compiler).
          draft: false
          prerelease: false
          generateReleaseNotes: true
