---
name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run ruff check (make lint-check)
        run: make lint-check
      - name: Run ruff format check (make format-check)
        run: make format-check
  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run markdownlint (make lint-markdown-check)
        run: make lint-markdown-check
  lint-yaml:
    name: Lint YAML
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run yamllint (make lint-yaml-check)
        run: make lint-yaml-check
  typecheck-python:
    name: Type-check Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run basedpyright (make typecheck)
        run: make typecheck
  test-python:
    name: Test Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run pytest (make test)
        run: make test
  test-python-coverage:
    name: Test Python Code Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run tests with coverage (make test-coverage)
        run: make test-coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            .coverage
            htmlcov/
            coverage.json
          retention-days: 30
      - name: Comment coverage on PR
        id: coverage_comment
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enforce minimum Overall coverage doesn't decrease
        if: ${{ steps.coverage_comment.outputs.new_num_statements && steps.coverage_comment.outputs.new_percent_covered < steps.coverage_comment.outputs.reference_percent_covered }}
        run: echo "Overall codebase coverage decreased." && exit 1
      - name: Enforce minimum PR coverage of 90%
        if: ${{ steps.coverage_comment.outputs.new_num_statements && steps.coverage_comment.outputs.new_percent_covered < 90 }}
        run: echo "This PR's coverage is below 90%." && exit 1
  test-python-cli:
    name: Test Python CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run smoke tests (make test-smoke)
        run: make test-smoke
  test-markdown-links:
    name: Validate Documentation Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Check documentation links (make test-links)
        run: make test-links
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Build documentation (make docs-build-quiet)
        run: make docs-build-quiet
  test-vscode-extension-python:
    name: Test VSCode Extension (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run Python tests for extension (make test-extension-python)
        run: make test-extension-python
  test-vscode-extension-typescript:
    name: Test VSCode Extension (TypeScript)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: vscode-extension/package-lock.json
      - name: Run TypeScript tests for extension (make test-extension-typescript)
        run: make test-extension-typescript
  test-vscode-extension-e2e:
    name: Test VSCode Extension E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: vscode-extension/package-lock.json
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run E2E tests for extension (make test-extension-e2e)
        run: make test-extension-e2e
  checks-passed:
    name: All Checks Passed
    runs-on: ubuntu-latest
    needs:
      - lint-python
      - lint-markdown
      - lint-yaml
      - typecheck-python
      - test-python
      - test-python-coverage
      - test-python-cli
      - test-markdown-links
      - build-docs
      - test-vscode-extension-python
      - test-vscode-extension-typescript
      - test-vscode-extension-e2e
    steps:
      - name: All Checks Passed
        run: echo "All checks passed"
