---
name: Publish to TestPyPI

on:
  push:
    tags:
      - 'test-v*'

jobs:
  build-and-publish:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/dashboard-compiler
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env

      - name: Build package
        run: uv build

      - name: Publish to TestPyPI
        run: uv publish --publish-url https://test.pypi.org/legacy/
