---
name: Test Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Test Coverage Report with PR Comments
  test-coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Run tests with coverage (make test-coverage)
        run: make test-coverage
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: |
            htmlcov/
            coverage.json
          retention-days: 30
      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@0b4822882443b98c09c51091ad20a7a556581c17 # v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
