# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Annotated

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.charts.base.view import KbnLayerColorMapping
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone


class KbnTagcloudVisualizationState(BaseRawVwModel):
    """Tagcloud visualization state in Kibana JSON.

    Note: Unlike pie/XY charts, tagcloud uses a flat structure without a layers array.
    The visualization state directly contains the layer ID and accessor configuration.
    """

    layerId: str | None = None
    'Layer ID reference for the data source.'
    tagAccessor: Annotated[str | None, OmitIfNone()] = Field(None)
    'Column ID for the bucketed dimension (tags/terms).'
    valueAccessor: Annotated[str | None, OmitIfNone()] = Field(None)
    'Column ID for the numeric metric dimension (frequency).'
    maxFontSize: int = Field(default=72)
    'Maximum font size for tags.'
    minFontSize: int = Field(default=12)
    'Minimum font size for tags.'
    orientation: str = Field(default='single')
    'Text orientation configuration.'
    showLabel: bool = Field(default=True)
    'Toggle for label visibility.'
    colorMapping: Annotated[KbnLayerColorMapping | None, OmitIfNone()] = None
    'Color mapping configuration for tag values.'
