"""Codegen script: generate permissive raw view models from Kbn* source view.py files.

Uses Python AST to parse and transform kb_dashboard_core view.py files into permissive
equivalents (BaseRawVwModel base, all fields optional). Class names are kept exactly as-is.

Run with:
    uv run python scripts/codegen_raw_models.py  (from repo root, in kb-dashboard-tools venv)
    or:
    cd packages/kb-dashboard-tools && uv run python ../../scripts/codegen_raw_models.py

Output:
    packages/kb-dashboard-tools/src/kb_dashboard_tools/decompile/kbn_raw_models/
"""

import ast
import shutil
import subprocess
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_SRC = REPO_ROOT / 'packages' / 'kb-dashboard-core' / 'src' / 'kb_dashboard_core'
OUT_DIR = (
    REPO_ROOT
    / 'packages'
    / 'kb-dashboard-tools'
    / 'src'
    / 'kb_dashboard_tools'
    / 'decompile'
    / 'kbn_raw_models'
)

GENERATED_HEADER = '# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT\n'

# Fields that may arrive as JSON-encoded strings; inject a mode='before' validator.
JSON_STRING_FIELDS = frozenset({
    'panelsJSON',
    'optionsJSON',
    'searchSourceJSON',
    'ignoreParentSettingsJSON',
})

# Base classes from kb_dashboard_core that we replace with BaseRawVwModel.
REPLACED_BASE_CLASSES = frozenset({'BaseVwModel', 'BaseModel'})

# Import names we always drop — they come from shared/view.py (BaseRawVwModel, OmitIfNone, RootDict).
DROPPED_IMPORT_NAMES = frozenset({'BaseVwModel', 'BaseModel', 'OmitIfNone', 'RootDict'})

# Pydantic decorators whose methods should be dropped entirely.
DROP_DECORATORS = frozenset({'model_validator', 'field_serializer', 'model_serializer'})

# Pydantic names to drop from pydantic imports (no longer needed in raw models).
DROPPED_PYDANTIC_NAMES = frozenset({'field_serializer', 'model_serializer', 'model_validator',
                                    'SerializerFunctionWrapHandler'})

BASE_CLASS_IMPORT = (
    'from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone, RootDict'
)

# ---------------------------------------------------------------------------
# AST transformer
# ---------------------------------------------------------------------------


class _RawModelTransformer(ast.NodeTransformer):
    """Transform a kb_dashboard_core view.py AST into a raw permissive view model."""

    def __init__(self) -> None:
        # Tracks whether we need field_validator in imports (for JSON-string validators).
        self.needs_field_validator = False
        # Tracks whether any field used `Any` (for typing imports).
        self.any_introduced = False
        # Names requiring JSON-string validators, collected per-class.
        self._json_fields_in_current_class: list[str] = []

    # ------------------------------------------------------------------
    # Imports
    # ------------------------------------------------------------------

    def visit_ImportFrom(self, node: ast.ImportFrom) -> ast.stmt | list[ast.stmt] | None:  # noqa: N802
        module = node.module or ''

        # Drop imports from shared modules; keep non-base names, remap module path.
        if module in ('kb_dashboard_core.shared.view', 'kb_dashboard_core.shared.model'):
            kept: list[ast.alias] = [
                a for a in node.names if a.name not in DROPPED_IMPORT_NAMES
            ]
            if not kept:
                return None  # drop the entire import
            sub = module[len('kb_dashboard_core.'):]
            new_module = f'kb_dashboard_tools.decompile.kbn_raw_models.{sub}'
            return ast.ImportFrom(module=new_module, names=kept, level=0)

        # Remap intra-core imports to kbn_raw_models.
        if module.startswith('kb_dashboard_core.'):
            sub = module[len('kb_dashboard_core.'):]
            new_module = f'kb_dashboard_tools.decompile.kbn_raw_models.{sub}'
            return ast.ImportFrom(module=new_module, names=node.names, level=0)

        # Drop unwanted pydantic names.
        if module == 'pydantic':
            kept_pydantic = [a for a in node.names if a.name not in DROPPED_PYDANTIC_NAMES]
            if not kept_pydantic:
                return None
            return ast.ImportFrom(module=module, names=kept_pydantic, level=0)

        # Everything else passes through unchanged (enum, typing, etc.).
        return node

    # ------------------------------------------------------------------
    # Class definitions
    # ------------------------------------------------------------------

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.stmt:  # noqa: N802
        # Replace base classes.
        new_bases: list[ast.expr] = []
        for base in node.bases:
            if isinstance(base, ast.Name) and base.id in REPLACED_BASE_CLASSES:
                new_bases.append(ast.Name(id='BaseRawVwModel', ctx=ast.Load()))
            else:
                # Recurse into base (handles e.g. RootModel[dict[...]])
                new_bases.append(self.visit(base))
        node.bases = new_bases

        # Track JSON fields for validator injection — reset per class.
        self._json_fields_in_current_class = []

        # Walk and transform the class body.
        new_body: list[ast.stmt] = []
        for stmt in node.body:
            transformed = self.visit(stmt)
            if transformed is None:
                continue  # node was dropped (e.g., @model_validator method)
            if isinstance(transformed, list):
                new_body.extend(transformed)
            else:
                new_body.append(transformed)

        # Inject JSON-string validators at end of class body.
        for field_name in self._json_fields_in_current_class:
            new_body.extend(_build_json_validator(field_name))
            self.needs_field_validator = True

        if not new_body:
            new_body = [ast.Pass()]
        node.body = new_body
        return node

    # ------------------------------------------------------------------
    # Function definitions (drop decorated methods)
    # ------------------------------------------------------------------

    def visit_FunctionDef(self, node: ast.FunctionDef) -> ast.stmt | None:  # noqa: N802
        for dec in node.decorator_list:
            if _decorator_name(dec) in DROP_DECORATORS:
                return None  # Drop the method entirely
        return node

    visit_AsyncFunctionDef = visit_FunctionDef  # type: ignore[assignment]

    # ------------------------------------------------------------------
    # Annotated assignments (make required fields optional)
    # ------------------------------------------------------------------

    def visit_AnnAssign(self, node: ast.AnnAssign) -> ast.stmt:  # noqa: N802
        if not isinstance(node.target, ast.Name):
            return node

        field_name = node.target.id

        # Track JSON fields in the current class.
        if field_name in JSON_STRING_FIELDS:
            self._json_fields_in_current_class.append(field_name)

        # Replace complex union type annotations with Any.
        node.annotation = _replace_complex_unions(node.annotation, self)

        # If the field has `= Field(...)` (positional ellipsis), make it optional.
        if node.value is not None and _is_field_required(node.value):
            node.annotation = _make_optional(node.annotation)
            node.value = _field_with_default_none(node.value)
        elif node.value is None:
            # Bare annotation with no default — make optional with `= None`.
            node.annotation = _make_optional(node.annotation)
            node.value = ast.Constant(value=None)

        return node


# ---------------------------------------------------------------------------
# AST helper functions
# ---------------------------------------------------------------------------


def _decorator_name(dec: ast.expr) -> str:
    """Return the base name of a decorator (handles Name, Attribute, and Call forms)."""
    if isinstance(dec, ast.Call):
        return _decorator_name(dec.func)
    if isinstance(dec, ast.Name):
        return dec.id
    if isinstance(dec, ast.Attribute):
        return dec.attr
    return ''


def _is_field_required(value: ast.expr) -> bool:
    """Return True if value is a `Field(...)` call with no default.

    Matches:
    - `Field(...)` — positional ellipsis
    - `Field(alias='...')` (or other keywords) with no `default=` or `default_factory=`
    """
    if not isinstance(value, ast.Call):
        return False
    func = value.func
    is_field = (isinstance(func, ast.Name) and func.id == 'Field') or (
        isinstance(func, ast.Attribute) and func.attr == 'Field'
    )
    if not is_field:
        return False
    # Positional ellipsis as first arg.
    if value.args and isinstance(value.args[0], ast.Constant) and value.args[0].value is ...:
        return True
    # No positional args and no default/default_factory keyword → required.
    if not value.args:
        kw_names = {kw.arg for kw in value.keywords}
        if 'default' not in kw_names and 'default_factory' not in kw_names:
            return True
    return False


def _make_optional(annotation: ast.expr) -> ast.expr:
    """Return `annotation | None` unless already optional."""
    if _annotation_has_none(annotation):
        return annotation
    return ast.BinOp(left=annotation, op=ast.BitOr(), right=ast.Constant(value=None))


def _annotation_has_none(annotation: ast.expr) -> bool:
    """Return True if the annotation already includes None."""
    if isinstance(annotation, ast.Constant) and annotation.value is None:
        return True
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        return _annotation_has_none(annotation.left) or _annotation_has_none(annotation.right)
    if isinstance(annotation, ast.Subscript):
        # Handle Optional[X]
        if isinstance(annotation.value, ast.Name) and annotation.value.id == 'Optional':
            return True
    return False


def _field_with_default_none(value: ast.expr) -> ast.expr:
    """Convert Field(...) to Field(default=None) by removing the positional ellipsis arg."""
    assert isinstance(value, ast.Call)
    new_args = [a for a in value.args if not (isinstance(a, ast.Constant) and a.value is ...)]
    new_keywords = [kw for kw in value.keywords if kw.arg != 'default']
    new_keywords.insert(0, ast.keyword(arg='default', value=ast.Constant(value=None)))
    return ast.Call(func=value.func, args=new_args, keywords=new_keywords)


def _replace_complex_unions(annotation: ast.expr, transformer: '_RawModelTransformer') -> ast.expr:
    """Replace complex union type annotations with Any.

    Targets:
    - dict[str, KbnLensColumnTypes]  → dict[str, Any]
    - list[KbnESQLColumnTypes]        → list[Any]
    - KbnFilterMetaTypes              → Any
    - KbnControlTypes                 → Any
    """
    # dict[str, KbnLensColumnTypes] → dict[str, Any]
    if (
        isinstance(annotation, ast.Subscript)
        and isinstance(annotation.value, ast.Name)
        and annotation.value.id == 'dict'
        and isinstance(annotation.slice, ast.Tuple)
        and len(annotation.slice.elts) == 2
        and isinstance(annotation.slice.elts[1], ast.Name)
        and annotation.slice.elts[1].id == 'KbnLensColumnTypes'
    ):
        transformer.any_introduced = True
        return ast.Subscript(
            value=ast.Name(id='dict', ctx=ast.Load()),
            slice=ast.Tuple(
                elts=[annotation.slice.elts[0], ast.Name(id='Any', ctx=ast.Load())],
                ctx=ast.Load(),
            ),
            ctx=ast.Load(),
        )

    # list[KbnESQLColumnTypes] → list[Any]
    if (
        isinstance(annotation, ast.Subscript)
        and isinstance(annotation.value, ast.Name)
        and annotation.value.id == 'list'
        and isinstance(annotation.slice, ast.Name)
        and annotation.slice.id == 'KbnESQLColumnTypes'
    ):
        transformer.any_introduced = True
        return ast.Subscript(
            value=ast.Name(id='list', ctx=ast.Load()),
            slice=ast.Name(id='Any', ctx=ast.Load()),
            ctx=ast.Load(),
        )

    # KbnFilterMetaTypes → Any
    if isinstance(annotation, ast.Name) and annotation.id == 'KbnFilterMetaTypes':
        transformer.any_introduced = True
        return ast.Name(id='Any', ctx=ast.Load())

    # KbnControlTypes → Any
    if isinstance(annotation, ast.Name) and annotation.id == 'KbnControlTypes':
        transformer.any_introduced = True
        return ast.Name(id='Any', ctx=ast.Load())

    # Walk into BinOp (union types like `X | Y | None`).
    if isinstance(annotation, ast.BinOp) and isinstance(annotation.op, ast.BitOr):
        annotation.left = _replace_complex_unions(annotation.left, transformer)
        annotation.right = _replace_complex_unions(annotation.right, transformer)
        return annotation

    # Walk into Subscript slices (e.g., Annotated[X, ...], list[X]).
    if isinstance(annotation, ast.Subscript):
        annotation.slice = _replace_complex_unions(annotation.slice, transformer)
        return annotation

    # Walk into Tuple elements (e.g., Annotated[X, Y, Z]).
    if isinstance(annotation, ast.Tuple):
        annotation.elts = [_replace_complex_unions(e, transformer) for e in annotation.elts]
        return annotation

    return annotation


def _build_json_validator(field_name: str) -> list[ast.stmt]:
    """Build AST nodes for a field_validator that parses a JSON string field."""
    src = textwrap.dedent(f"""\
        @field_validator('{field_name}', mode='before')
        @classmethod
        def _parse_{field_name}_json(cls, v: object) -> object:
            if isinstance(v, str):
                from typing import cast as _cast
                import json as _json
                return _cast(object, _json.loads(v))
            return v
    """)
    tree = ast.parse(src)
    return tree.body


# ---------------------------------------------------------------------------
# Post-transformation fixes
# ---------------------------------------------------------------------------


def _ensure_any_import(tree: ast.Module) -> None:
    """Ensure `Any` is imported from typing in the module."""
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == 'typing':
            names = [a.name for a in node.names]
            if 'Any' not in names:
                node.names.append(ast.alias(name='Any'))
            return
    # No typing import yet — insert one after the last import.
    insert_pos = 0
    for i, node in enumerate(tree.body):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            insert_pos = i + 1
    tree.body.insert(insert_pos, ast.ImportFrom(module='typing', names=[ast.alias(name='Any')], level=0))


def _ensure_field_validator_import(tree: ast.Module) -> None:
    """Ensure `field_validator` is imported from pydantic."""
    for node in tree.body:
        if isinstance(node, ast.ImportFrom) and node.module == 'pydantic':
            names = [a.name for a in node.names]
            if 'field_validator' not in names:
                node.names.append(ast.alias(name='field_validator'))
            return
    insert_pos = 0
    for i, node in enumerate(tree.body):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            insert_pos = i + 1
    tree.body.insert(
        insert_pos,
        ast.ImportFrom(module='pydantic', names=[ast.alias(name='field_validator')], level=0),
    )


def _override_panels_json_annotation(tree: ast.Module) -> bool:
    """Change panelsJSON annotation to list[Any] | None.

    The strict model has `panelsJSON: list[KbnBasePanel]`. After transformation the
    annotation becomes `list[KbnBasePanel] | None`. We want `list[Any] | None` so panel
    subtypes can be validated separately.

    Returns True if Any was introduced.
    """
    any_introduced = False
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == 'panelsJSON'
            and 'KbnBasePanel' in ast.unparse(node.annotation)
        ):
            node.annotation = ast.BinOp(
                left=ast.Subscript(
                    value=ast.Name(id='list', ctx=ast.Load()),
                    slice=ast.Name(id='Any', ctx=ast.Load()),
                    ctx=ast.Load(),
                ),
                op=ast.BitOr(),
                right=ast.Constant(value=None),
            )
            node.value = ast.Constant(value=None)
            any_introduced = True
    return any_introduced


def _add_validation_aliases(tree: ast.Module) -> None:
    """For any Field with serialization_alias but no validation_alias, add validation_alias."""
    for node in ast.walk(tree):
        if not isinstance(node, ast.AnnAssign) or not isinstance(node.value, ast.Call):
            continue
        call = node.value
        kw_names = [kw.arg for kw in call.keywords]
        if 'serialization_alias' in kw_names and 'validation_alias' not in kw_names:
            for kw in call.keywords:
                if kw.arg == 'serialization_alias':
                    idx = call.keywords.index(kw)
                    call.keywords.insert(
                        idx,
                        ast.keyword(arg='validation_alias', value=kw.value),
                    )
                    break


# ---------------------------------------------------------------------------
# Per-file transformation
# ---------------------------------------------------------------------------


def _compute_relative_module(src_path: Path) -> str:
    """Return the dotted module path relative to kb_dashboard_core root."""
    rel = src_path.relative_to(CORE_SRC)
    parts = list(rel.parts)
    parts[-1] = parts[-1].removesuffix('.py')
    return '.'.join(parts)


def _transform_source(source: str, src_path: Path) -> str:
    """Full AST-based transformation of one source view.py → raw model file content."""
    tree = ast.parse(source)

    # Only process files that define Kbn* classes at the top level.
    has_kbn_classes = any(
        isinstance(node, ast.ClassDef) and node.name.startswith('Kbn')
        for node in tree.body
    )
    if not has_kbn_classes:
        return ''

    # Drop the source module docstring (if any) — we'll prepend our own header.
    if (
        tree.body
        and isinstance(tree.body[0], ast.Expr)
        and isinstance(tree.body[0].value, ast.Constant)
        and isinstance(tree.body[0].value.value, str)
    ):
        tree.body.pop(0)

    transformer = _RawModelTransformer()
    transformed = transformer.visit(tree)
    ast.fix_missing_locations(transformed)

    # Override panelsJSON annotation to list[Any] after transformation.
    if _override_panels_json_annotation(transformed):
        transformer.any_introduced = True

    # Add validation_alias where only serialization_alias exists.
    _add_validation_aliases(transformed)

    # Ensure Any is imported if needed.
    if transformer.any_introduced:
        _ensure_any_import(transformed)

    # Ensure field_validator is imported if validators were injected.
    if transformer.needs_field_validator:
        _ensure_field_validator_import(transformed)

    # Insert BaseRawVwModel import after the last existing import.
    base_import = ast.parse(BASE_CLASS_IMPORT).body[0]
    insert_pos = 0
    for i, node in enumerate(transformed.body):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            insert_pos = i + 1
    transformed.body.insert(insert_pos, base_import)
    ast.fix_missing_locations(transformed)

    # Unparse back to source.
    code = ast.unparse(transformed)

    header = (
        GENERATED_HEADER
        + '"""Permissive view models generated from kb_dashboard_core view models."""\n\n'
    )
    return header + code + '\n'


# ---------------------------------------------------------------------------
# Shared view template (hand-written, not generated)
# ---------------------------------------------------------------------------

SHARED_VIEW_CONTENT = GENERATED_HEADER + textwrap.dedent("""\
    \"\"\"Permissive base model and shared types for kbn_raw_models.\"\"\"

    from typing import ClassVar

    from pydantic import BaseModel as PydanticBaseModel
    from pydantic import ConfigDict

    from kb_dashboard_core.shared.view import KbnReference, OmitIfNone, RootDict  # re-exports for generated modules

    __all__ = ['BaseRawVwModel', 'KbnReference', 'OmitIfNone', 'RootDict']


    class BaseRawVwModel(PydanticBaseModel):
        \"\"\"Permissive base for raw Kibana view models — extra fields are ignored, strict mode off.\"\"\"

        model_config: ClassVar[ConfigDict] = ConfigDict(
            strict=False,
            extra='ignore',
            frozen=False,
            populate_by_name=True,
            use_enum_values=True,
        )
""")


# ---------------------------------------------------------------------------
# File-writing helpers
# ---------------------------------------------------------------------------


def _out_path(src_path: Path) -> Path:
    """Map source view.py → output .py path."""
    rel = src_path.relative_to(CORE_SRC)
    return OUT_DIR / rel


def _write_init(path: Path) -> None:
    """Ensure __init__.py exists at path (only if it doesn't already)."""
    if not path.exists():
        path.write_text(GENERATED_HEADER + '\n')


def _write_shared_view(out_dir: Path) -> None:
    """Write the hand-crafted shared/view.py."""
    shared_dir = out_dir / 'shared'
    shared_dir.mkdir(parents=True, exist_ok=True)
    _write_init(shared_dir / '__init__.py')
    (shared_dir / 'view.py').write_text(SHARED_VIEW_CONTENT)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    """Generate all raw model files."""
    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []

    # Write shared/view.py manually.
    _write_shared_view(OUT_DIR)

    for src_path in sorted(CORE_SRC.rglob('view.py')):
        if src_path.parent.name == 'shared':
            continue  # Handled manually above

        source = src_path.read_text()
        code = _transform_source(source, src_path)
        if not code:
            continue

        out = _out_path(src_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        # Ensure __init__.py exists at every package level between OUT_DIR and out.parent.
        pkg_dir = out.parent
        while pkg_dir != OUT_DIR.parent:
            _write_init(pkg_dir / '__init__.py')
            pkg_dir = pkg_dir.parent

        out.write_text(code)
        generated.append(out)
        print(f'  wrote: {out.relative_to(REPO_ROOT)}')

    # Write top-level __init__.py that re-exports KbnDashboard for convenience.
    init_path = OUT_DIR / '__init__.py'
    init_path.write_text(
        GENERATED_HEADER
        + '"""Permissive view models for parsing real-world Kibana dashboard JSON."""\n\n'
        + 'from kb_dashboard_tools.decompile.kbn_raw_models.dashboard.view import KbnDashboard\n\n'
        + "__all__ = ['KbnDashboard']\n"
    )

    print(f'\nGenerated {len(generated)} files in {OUT_DIR.relative_to(REPO_ROOT)}')

    # Auto-format with ruff to ensure CI passes.
    tools_dir = REPO_ROOT / 'packages' / 'kb-dashboard-tools'

    ruff_check = subprocess.run(
        ['uv', 'run', 'ruff', 'check', '--fix', str(OUT_DIR)],
        cwd=tools_dir,
        capture_output=True,
        text=True,
    )
    if ruff_check.returncode != 0:
        raise SystemExit(f'ruff check --fix failed:\n{ruff_check.stdout[:1000]}{ruff_check.stderr[:1000]}')
    print('ruff check --fix: OK')

    ruff_result = subprocess.run(
        ['uv', 'run', 'ruff', 'format', str(OUT_DIR)],
        cwd=tools_dir,
        capture_output=True,
        text=True,
    )
    if ruff_result.returncode != 0:
        raise SystemExit(f'ruff format failed:\n{ruff_result.stdout[:1000]}{ruff_result.stderr[:1000]}')
    print('ruff format: OK')


if __name__ == '__main__':
    main()
