"""Codegen script: generate KbnRaw* permissive view models from Kbn* source view.py files.

Uses Python AST to parse source view.py files, transforms class definitions, and emits
the generated KbnRaw* models to kbn_raw_models/ in kb-dashboard-tools.

Run with:
    uv run python scripts/codegen_raw_models.py  (from repo root, in kb-dashboard-tools venv)
    or:
    cd packages/kb-dashboard-tools && uv run python ../../scripts/codegen_raw_models.py

Output:
    packages/kb-dashboard-tools/src/kb_dashboard_tools/decompile/kbn_raw_models/
"""

import ast
import textwrap
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT = Path(__file__).resolve().parent.parent
CORE_SRC = REPO_ROOT / 'packages' / 'kb-dashboard-core' / 'src' / 'kb_dashboard_core'
OUT_DIR = (
    REPO_ROOT
    / 'packages'
    / 'kb-dashboard-tools'
    / 'src'
    / 'kb_dashboard_tools'
    / 'decompile'
    / 'kbn_raw_models'
)

GENERATED_HEADER = '# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT\n'

# Fields that may arrive as JSON-encoded strings; inject a mode='before' validator.
JSON_STRING_FIELDS = frozenset({
    'panelsJSON',
    'optionsJSON',
    'searchSourceJSON',
    'ignoreParentSettingsJSON',
})

# Base classes from kb_dashboard_core that we replace with BaseRawVwModel.
REPLACED_BASE_CLASSES = frozenset({'BaseVwModel', 'BaseModel'})

# Imports we always drop — they come from BASE_CLASS_BLOCK (BaseRawVwModel, OmitIfNone, RootDict).
DROPPED_IMPORT_NAMES = frozenset({'BaseVwModel', 'BaseModel', 'OmitIfNone', 'RootDict'})

BASE_CLASS_BLOCK = textwrap.dedent("""\
    from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone, RootDict
""")


# ---------------------------------------------------------------------------
# Helpers: rename Kbn* → KbnRaw*
# ---------------------------------------------------------------------------


def kbn_to_raw(name: str) -> str:
    """Rename Kbn* → KbnRaw*. Non-Kbn names are returned unchanged."""
    if name.startswith('Kbn'):
        return 'KbnRaw' + name[3:]
    return name


def rename_in_source(source: str, kbn_names: set[str]) -> str:
    """Do a global search-replace of every known Kbn* name in a source string.

    We rename in reverse-length order so that e.g. KbnFormBasedDataSourceStateLayer is
    renamed before KbnFormBasedDataSourceState.
    """
    for name in sorted(kbn_names, key=len, reverse=True):
        source = source.replace(name, kbn_to_raw(name))
    return source


# ---------------------------------------------------------------------------
# Collecting all Kbn* class names across the entire core package
# ---------------------------------------------------------------------------


def collect_all_kbn_names() -> set[str]:
    """Walk all view.py files in kb_dashboard_core and return every Kbn* name.

    Includes both class definitions and type aliases (PEP 695 `type X = ...`).
    """
    names: set[str] = set()
    for path in CORE_SRC.rglob('view.py'):
        try:
            tree = ast.parse(path.read_text())
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name.startswith('Kbn'):
                names.add(node.name)
            elif isinstance(node, ast.TypeAlias) and isinstance(node.name, ast.Name):
                if node.name.id.startswith('Kbn'):
                    names.add(node.name.id)
    return names


# ---------------------------------------------------------------------------
# Per-file transformation
# ---------------------------------------------------------------------------


def _compute_relative_module(src_path: Path) -> str:
    """Return the dotted module path relative to kb_dashboard_core root.

    e.g. controls/view.py → controls.view
    """
    rel = src_path.relative_to(CORE_SRC)
    parts = list(rel.parts)
    parts[-1] = parts[-1].removesuffix('.py')
    return '.'.join(parts)


def _transform_source(source: str, src_path: Path, all_kbn_names: set[str]) -> str:
    """Full transformation of one source view.py → KbnRaw* file content."""
    tree = ast.parse(source)

    # -----------------------------------------------------------------------
    # 1. Collect what's defined in this file
    # -----------------------------------------------------------------------
    local_kbn_names: set[str] = set()
    local_non_kbn_classes: set[str] = set()

    for node in tree.body:
        if isinstance(node, ast.ClassDef):
            if node.name.startswith('Kbn'):
                local_kbn_names.add(node.name)
            else:
                local_non_kbn_classes.add(node.name)

    if len(local_kbn_names) == 0:
        return ''  # Nothing to generate

    # -----------------------------------------------------------------------
    # 2. Gather original source lines for precise slicing
    # -----------------------------------------------------------------------
    lines = source.splitlines(keepends=True)

    # -----------------------------------------------------------------------
    # 3. Build new imports section
    # -----------------------------------------------------------------------
    import_lines: list[str] = []
    seen_imports: set[str] = set()

    def _add_import(line: str) -> None:
        stripped = line.strip()
        if stripped not in seen_imports and len(stripped) > 0:
            seen_imports.add(stripped)
            import_lines.append(line.rstrip())

    # Process original import statements
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            if isinstance(node, ast.ImportFrom):
                module = node.module or ''

                # Drop base class imports from shared modules; keep other names and remap to kbn_raw_models.
                if module in ('kb_dashboard_core.shared.view', 'kb_dashboard_core.shared.model'):
                    kbn_keep = []   # Kbn* names → remap to kbn_raw_models.shared.view
                    non_kbn_keep = []  # non-Kbn* names (OmitIfNone, RootDict, etc.) → keep from core
                    for alias in node.names:
                        if alias.name in DROPPED_IMPORT_NAMES:
                            continue  # Drop base class
                        if alias.name in all_kbn_names:
                            kbn_keep.append(alias)
                        else:
                            non_kbn_keep.append(alias)

                    if len(kbn_keep) > 0:
                        raw_names = [
                            kbn_to_raw(a.name) if a.asname is None else f'{kbn_to_raw(a.name)} as {kbn_to_raw(a.asname)}'
                            for a in kbn_keep
                        ]
                        sub = module[len('kb_dashboard_core.'):]
                        _add_import(f'from kb_dashboard_tools.decompile.kbn_raw_models.{sub} import {", ".join(raw_names)}')
                    if len(non_kbn_keep) > 0:
                        names_str = ', '.join(
                            a.name if a.asname is None else f'{a.name} as {a.asname}'
                            for a in non_kbn_keep
                        )
                        _add_import(f'from {module} import {names_str}')
                    continue

                # Translate intra-core imports → kbn_raw_models imports.
                if module.startswith('kb_dashboard_core.'):
                    sub = module[len('kb_dashboard_core.'):]
                    raw_names = []
                    for alias in node.names:
                        raw_name = kbn_to_raw(alias.name) if alias.name in all_kbn_names else alias.name
                        raw_asname = kbn_to_raw(alias.asname) if alias.asname and alias.asname in all_kbn_names else alias.asname
                        if raw_asname is not None:
                            raw_names.append(f'{raw_name} as {raw_asname}')
                        else:
                            raw_names.append(raw_name)
                    names_str = ', '.join(raw_names)
                    _add_import(f'from kb_dashboard_tools.decompile.kbn_raw_models.{sub} import {names_str}')
                    continue

                # Drop field_serializer — not needed in raw models.
                if module == 'pydantic':
                    keep = []
                    for alias in node.names:
                        if alias.name == 'field_serializer':
                            continue  # Drop
                        keep.append(alias)
                    if len(keep) > 0:
                        names_str = ', '.join(
                            a.name if a.asname is None else f'{a.name} as {a.asname}'
                            for a in keep
                        )
                        _add_import(f'from {module} import {names_str}')
                    continue

                # Everything else passes through.
                names_str = ', '.join(
                    a.name if a.asname is None else f'{a.name} as {a.asname}'
                    for a in node.names
                )
                _add_import(f'from {module} import {names_str}')

            else:  # plain import
                names_str = ', '.join(
                    a.name if a.asname is None else f'{a.name} as {a.asname}'
                    for a in node.names
                )
                _add_import(f'import {names_str}')

    # Ensure field_validator is imported (needed for JSON-string validators).
    pydantic_line_idx = next(
        (i for i, ln in enumerate(import_lines) if ln.startswith('from pydantic import')), None
    )
    if pydantic_line_idx is not None:
        if 'field_validator' not in import_lines[pydantic_line_idx]:
            import_lines[pydantic_line_idx] += ', field_validator'
    else:
        import_lines.insert(0, 'from pydantic import field_validator')

    # -----------------------------------------------------------------------
    # 4. Extract class bodies, dropping @field_serializer / @model_validator
    # -----------------------------------------------------------------------

    def _get_node_source(node: ast.AST) -> str:
        """Extract source text for an AST node using line/col info."""
        assert isinstance(node, ast.stmt)
        start_line = node.lineno - 1
        end_line = node.end_lineno  # exclusive index
        return ''.join(lines[start_line:end_line])

    def _transform_class_body(cls_node: ast.ClassDef, class_source: str) -> str:
        """Return class source with serializer methods stripped and JSON validators added."""
        # Determine which methods to drop.
        drop_ranges: list[tuple[int, int]] = []  # (start_line, end_line) 1-based, inclusive

        json_fields_in_class: list[str] = []

        for stmt in cls_node.body:
            # Collect annotated fields that need JSON parsing.
            if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
                field_name = stmt.target.id
                if field_name in JSON_STRING_FIELDS:
                    json_fields_in_class.append(field_name)

            # Mark methods to drop.
            if isinstance(stmt, ast.FunctionDef):
                for dec in stmt.decorator_list:
                    drop = False
                    if isinstance(dec, ast.Call):
                        func = dec.func
                        if isinstance(func, ast.Name) and func.id in ('model_validator', 'field_serializer'):
                            drop = True
                        if isinstance(func, ast.Attribute) and func.attr in ('model_validator', 'field_serializer'):
                            drop = True
                    elif isinstance(dec, ast.Name) and dec.id in ('model_validator', 'field_serializer'):
                        drop = True
                    elif isinstance(dec, ast.Attribute) and dec.attr in ('model_validator', 'field_serializer'):
                        drop = True
                    if drop:
                        # start_line/end_line are relative to the file, not the class.
                        # We need to get the decorator start (first decorator).
                        first_dec = stmt.decorator_list[0]
                        drop_ranges.append((first_dec.lineno, stmt.end_lineno))
                        break

        if len(drop_ranges) == 0 and len(json_fields_in_class) == 0:
            return class_source

        # Re-split the source so we can remove lines.
        src_lines = class_source.splitlines(keepends=True)
        # drop_ranges are 1-based file line numbers; convert to 0-based within class_source
        cls_start = cls_node.lineno  # 1-based line number in the file

        result_lines: list[str] = []
        for i, line in enumerate(src_lines):
            file_line = cls_start + i  # 1-based file line
            dropped = any(start <= file_line <= end for start, end in drop_ranges)
            if not dropped:
                result_lines.append(line)

        result = ''.join(result_lines)
        # Add JSON validators at the end of the class.
        if len(json_fields_in_class) > 0:
            for field_name in json_fields_in_class:
                # Build validator lines with explicit 4-space indentation (no dedent).
                validator_lines = [
                    '',
                    f"    @field_validator('{field_name}', mode='before')",
                    '    @classmethod',
                    f'    def _parse_{field_name}_json(cls, v: object) -> object:',
                    '        if isinstance(v, str):',
                    '            import json as _json',
                    '            return _json.loads(v)  # pyright: ignore[reportAny]',
                    '        return v',
                ]
                result = result.rstrip('\n') + '\n'.join(validator_lines) + '\n'
        return result

    # -----------------------------------------------------------------------
    # 5. Collect all class definitions (Kbn* and non-Kbn* helper classes)
    #    Type aliases too.
    # -----------------------------------------------------------------------
    class_sections: list[str] = []

    # Collect TYPE_CHECKING block (forward refs) — keep but rename contents
    tc_block: str | None = None
    for node in tree.body:
        if isinstance(node, ast.If):
            # Check for `if TYPE_CHECKING:`
            test = node.test
            if isinstance(test, ast.Name) and test.id == 'TYPE_CHECKING':
                tc_block = _get_node_source(node)
                break

    # Names that get replaced with simple types (Any etc.) in field annotations.
    # We skip emitting type alias definitions for these — they'd produce e.g. `type Any = ...`
    # after the rename + complex_union_replacements post-processing steps.
    # Also skip any alias that references a dropped alias (e.g. KbnRawColumnTypes = KbnRawLensColumnTypes | ...).
    complex_union_raw_names = {
        'KbnRawFilterMetaTypes',
        'KbnRawControlTypes',
        'KbnRawLensColumnTypes',
        'KbnRawESQLColumnTypes',
        'KbnRawColumnTypes',  # references KbnRawLensColumnTypes and KbnRawESQLColumnTypes
    }

    for node in tree.body:
        # Type aliases (e.g., `type KbnXYLegendSize = Literal[...]`)
        if isinstance(node, ast.TypeAlias) and isinstance(node.name, ast.Name):
            raw_alias_name = kbn_to_raw(node.name.id)
            if raw_alias_name in complex_union_raw_names:
                continue  # Skip — this alias definition gets replaced with Any in field annotations
            alias_src = _get_node_source(node)
            class_sections.append(alias_src)

        # Assignment aliases (e.g., `KbnColumnTypes = ...` or `LegendPositionType = Literal[...]`)
        # These appear as ast.Assign with a Name target.
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    name = target.id
                    raw_name = kbn_to_raw(name)
                    if raw_name in complex_union_raw_names:
                        break  # Skip complex union assignments too
                    # Include Kbn* names AND UpperCase type aliases (e.g. LegendPositionType)
                    if name.startswith('Kbn') or (name[0].isupper() and not name.isupper()):
                        class_sections.append(_get_node_source(node))
                        break

        # Class definitions — both Kbn* and non-Kbn* helpers (enums, etc.)
        elif isinstance(node, ast.ClassDef):
            class_src = _transform_class_body(node, _get_node_source(node))
            class_sections.append(class_src)

    # -----------------------------------------------------------------------
    # 6. Assemble the final file
    # -----------------------------------------------------------------------
    combined_classes = '\n'.join(class_sections)

    # Replace all Kbn* names with KbnRaw* throughout the entire class section.
    combined_classes = rename_in_source(combined_classes, all_kbn_names)

    # Fix base class inheritance: replace BaseVwModel/BaseModel → BaseRawVwModel
    for old_base in ('BaseVwModel', 'BaseModel'):
        combined_classes = combined_classes.replace(f'({old_base})', '(BaseRawVwModel)')
        combined_classes = combined_classes.replace(f'({old_base},', '(BaseRawVwModel,')
        combined_classes = combined_classes.replace(f', {old_base})', ', BaseRawVwModel)')
        combined_classes = combined_classes.replace(f', {old_base},', ', BaseRawVwModel,')

    # Post-processing: make all Field(...) optional — raw models should not fail on missing fields.
    import re

    # Step 1: Replace Field(...) markers with Field(default=None).
    # Single-line: `= Field(...)`
    combined_classes = re.sub(r'= Field\(\.\.\.\)', '= Field(default=None)', combined_classes)
    # Multi-line: `= Field(\n        ...,`
    combined_classes = re.sub(r'= Field\(\s*\.\.\.,', '= Field(default=None,', combined_classes)

    # Step 2: After the replacements above, add `| None` to any field type annotation
    # that now has `= Field(default=None` but lacks `| None` in its type.
    # This covers both single-line and multi-line Field cases.
    # Pattern: `    fieldname: SomeType = Field(default=None` on one line.
    def _add_none_to_type(m: re.Match[str]) -> str:
        indent = m.group(1)
        field_name = m.group(2)
        type_anno = m.group(3)
        rest = m.group(4)
        if '| None' not in type_anno and type_anno.strip() != 'None':
            type_anno = type_anno.rstrip() + ' | None'
        return f'{indent}{field_name}: {type_anno} = Field(default=None{rest}'

    combined_classes = re.sub(
        r'^( +)([a-zA-Z_][a-zA-Z0-9_]*): ([^\n=]+?) = Field\(default=None([\),])',
        _add_none_to_type,
        combined_classes,
        flags=re.MULTILINE,
    )

    # Replace complex union types with Any — these unions have Literal discriminators
    # that fail when real Kibana JSON has missing fields or unexpected values.
    # The raw models are for permissive parsing; typed access can be done per-field separately.
    complex_union_replacements = {
        # Lens column types — complex union of typed columns with Literal operationType discriminators.
        # Both renamed (KbnRaw*) and un-renamed variants in case type alias rename didn't apply.
        'dict[str, KbnRawLensColumnTypes]': 'dict[str, Any]',
        'dict[str, KbnLensColumnTypes]': 'dict[str, Any]',
        'list[KbnRawESQLColumnTypes]': 'list[Any]',
        'list[KbnESQLColumnTypes]': 'list[Any]',
        # Filter meta types — union with Literal type discriminators
        'KbnRawFilterMetaTypes': 'Any',
        'KbnFilterMetaTypes': 'Any',
        # Control types — union with Literal type discriminators
        'KbnRawControlTypes': 'Any',
        'KbnControlTypes': 'Any',
    }
    any_introduced = False
    for old_type, new_type in complex_union_replacements.items():
        if old_type in combined_classes:
            combined_classes = combined_classes.replace(old_type, new_type)
            if 'Any' in new_type:
                any_introduced = True

    # If complex_union_replacements introduced `Any`, ensure it's in the typing imports.
    if any_introduced:
        typing_line_idx = next(
            (i for i, ln in enumerate(import_lines) if 'from typing import' in ln), None
        )
        if typing_line_idx is not None:
            if 'Any' not in import_lines[typing_line_idx]:
                import_lines[typing_line_idx] = import_lines[typing_line_idx].rstrip() + ', Any'
        else:
            import_lines.insert(0, 'from typing import Any')

    # Change panelsJSON to list[Any] so panel subtypes (KbnRawLensPanel etc.) can be validated
    # separately — KbnRawBasePanel with extra='ignore' drops embeddableConfig data.
    if 'panelsJSON: list[KbnRawBasePanel]' in combined_classes:
        combined_classes = combined_classes.replace(
            'panelsJSON: list[KbnRawBasePanel]',
            'panelsJSON: list[Any] | None = None',
        )
        # Ensure Any is in the typing imports for this file.
        pydantic_line_idx = next(
            (i for i, ln in enumerate(import_lines) if 'from typing import' in ln), None
        )
        if pydantic_line_idx is not None:
            if 'Any' not in import_lines[pydantic_line_idx]:
                import_lines[pydantic_line_idx] = import_lines[pydantic_line_idx].rstrip() + ', Any'
        else:
            import_lines.insert(0, 'from typing import Any')

    # Fix serialization_alias-only fields so they also have a validation_alias.
    # e.g. Field(default=None, serialization_alias='$state') ->
    #      Field(default=None, validation_alias='$state', serialization_alias='$state')
    def _add_validation_alias(m: re.Match[str]) -> str:
        alias_value = m.group(1)
        original = m.group(0)
        if 'validation_alias' in original:
            return original  # already has one
        return original.replace(
            f"serialization_alias='{alias_value}'",
            f"validation_alias='{alias_value}', serialization_alias='{alias_value}'",
        )
    combined_classes = re.sub(
        r"Field\([^)]*serialization_alias='([^']+)'[^)]*\)",
        _add_validation_alias,
        combined_classes,
    )

    # Post-processing: make bare required fields (no default) optional.
    # Match lines like `    fieldname: SomeType` that don't already have a default.
    # Pattern: line starts with whitespace, identifier, colon, type, and ends there (no '=').
    def _optionalize_bare_field(m: re.Match[str]) -> str:
        indent_ws = m.group(1)
        field_name = m.group(2)
        type_anno = m.group(3).rstrip()
        # Skip class/def/special lines
        if field_name in ('class', 'def', 'return', 'pass', 'else', 'elif'):
            return m.group(0)
        # Skip if type already allows None
        if '| None' in type_anno or 'None' == type_anno:
            return m.group(0)
        return f'{indent_ws}{field_name}: {type_anno} | None = None\n'

    # Only optionalize inside class bodies (4-space indent), not module-level type aliases.
    combined_classes = re.sub(
        r'^(    )([a-zA-Z_][a-zA-Z0-9_]*): ([^\n=]+)\n',
        _optionalize_bare_field,
        combined_classes,
        flags=re.MULTILINE,
    )

    # TYPE_CHECKING block: rename Kbn* inside it
    if tc_block is not None:
        tc_renamed = rename_in_source(tc_block, all_kbn_names)
    else:
        tc_renamed = None

    parts: list[str] = [
        GENERATED_HEADER,
        '"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""\n',
        BASE_CLASS_BLOCK,
    ]

    if len(import_lines) > 0:
        parts.append('\n'.join(import_lines))
        parts.append('')

    if tc_renamed is not None:
        parts.append(tc_renamed)
        parts.append('')

    parts.append(combined_classes)

    return '\n'.join(parts)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


SHARED_VIEW_CONTENT = GENERATED_HEADER + textwrap.dedent("""\
    \"\"\"Raw permissive KbnRaw* view models for kb_dashboard_core shared types.\"\"\"

    from typing import ClassVar, TypeVar

    from pydantic import BaseModel as PydanticBaseModel
    from pydantic import ConfigDict, Field, RootModel

    from kb_dashboard_core.shared.view import OmitIfNone, RootDict  # re-export for generated modules

    __all__ = ['BaseRawVwModel', 'OmitIfNone', 'RootDict', 'KbnRawReference']

    T = TypeVar('T')


    class BaseRawVwModel(PydanticBaseModel):
        \"\"\"Permissive base for raw Kibana view models — extra fields are ignored, strict mode off.\"\"\"

        model_config: ClassVar[ConfigDict] = ConfigDict(
            strict=False,
            extra='ignore',
            frozen=False,
            populate_by_name=True,
            use_enum_values=True,
        )


    class KbnRawReference(BaseRawVwModel):
        \"\"\"Represents a reference object in the Kibana JSON structure.\"\"\"

        type: str = Field(default='')
        \"\"\"The type of the referenced object, e.g., 'index-pattern', 'visualization', 'dashboard'.\"\"\"

        id: str = Field(default='')
        \"\"\"The unique or friendly identifier of the referenced object.\"\"\"

        name: str = Field(default='')
        \"\"\"A sometimes namespaced identifier for the reference.\"\"\"
""")


def _write_shared_view(out_dir: Path, all_kbn_names: set[str]) -> None:  # noqa: ARG001
    """Write a manually-crafted shared/view.py for the kbn_raw_models package."""
    shared_dir = out_dir / 'shared'
    shared_dir.mkdir(parents=True, exist_ok=True)
    _write_init(shared_dir / '__init__.py')
    (shared_dir / 'view.py').write_text(SHARED_VIEW_CONTENT)


def _out_path(src_path: Path) -> Path:
    """Map source view.py → output .py path."""
    rel = src_path.relative_to(CORE_SRC)
    return OUT_DIR / rel


def _write_init(path: Path) -> None:
    """Ensure __init__.py exists at path (only if it doesn't already)."""
    if not path.exists():
        path.write_text(GENERATED_HEADER + '\n')


def main() -> None:
    """Generate all KbnRaw* model files."""
    all_kbn_names = collect_all_kbn_names()
    print(f'Discovered {len(all_kbn_names)} Kbn* classes across kb_dashboard_core')

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []
    # Write the shared/view.py manually — it has special types (TypeVar, RootModel)
    # that the codegen cannot handle generically.
    _write_shared_view(OUT_DIR, all_kbn_names)

    for src_path in sorted(CORE_SRC.rglob('view.py')):
        if src_path.parent.name == 'shared':
            continue  # Handled manually above

        source = src_path.read_text()
        code = _transform_source(source, src_path, all_kbn_names)
        if len(code) == 0:
            continue

        out = _out_path(src_path)
        out.parent.mkdir(parents=True, exist_ok=True)

        # Ensure __init__.py exists at every package level between OUT_DIR and out.parent.
        pkg_dir = out.parent
        while pkg_dir != OUT_DIR.parent:
            _write_init(pkg_dir / '__init__.py')
            pkg_dir = pkg_dir.parent

        out.write_text(code)
        generated.append(out)
        print(f'  wrote: {out.relative_to(REPO_ROOT)}')

    # Write top-level __init__.py that re-exports KbnRawDashboard for convenience.
    init_path = OUT_DIR / '__init__.py'
    init_path.write_text(
        GENERATED_HEADER
        + '"""KbnRaw* permissive view models for parsing real-world Kibana dashboard JSON."""\n\n'
        + 'from kb_dashboard_tools.decompile.kbn_raw_models.dashboard.view import KbnRawDashboard\n\n'
        + '__all__ = [\'KbnRawDashboard\']\n'
    )

    print(f'\nGenerated {len(generated)} files in {OUT_DIR.relative_to(REPO_ROOT)}')

    # Auto-format with ruff to ensure CI passes.
    # Order matters: run check --fix first (removes unused imports, etc.), then format
    # (fixes whitespace/blank lines after imports were removed). A second format pass
    # ensures files left by check --fix are also properly formatted.
    import subprocess
    tools_dir = REPO_ROOT / 'packages' / 'kb-dashboard-tools'

    ruff_check = subprocess.run(
        ['uv', 'run', 'ruff', 'check', '--fix', str(OUT_DIR)],
        cwd=tools_dir,
        capture_output=True,
        text=True,
    )
    if ruff_check.returncode == 0:
        print('ruff check --fix: OK')
    else:
        print(f'ruff check --fix output: {ruff_check.stdout[:500]}')

    # Run format AFTER check --fix so any whitespace/blank-line changes from import removal
    # are normalized.
    ruff_result = subprocess.run(
        ['uv', 'run', 'ruff', 'format', str(OUT_DIR)],
        cwd=tools_dir,
        capture_output=True,
        text=True,
    )
    if ruff_result.returncode == 0:
        print('ruff format: OK')
    else:
        print(f'ruff format warning: {ruff_result.stderr}')


if __name__ == '__main__':
    main()
