---
name: Setup Python Environment
description: Set up Python and install UV package manager with dependencies
runs:
  using: composite
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install UV
      uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      shell: bash
      run: uv sync --group dev --extra lsp
    - name: Install markdownlint-cli
      shell: bash
      run: npm install -g markdownlint-cli
