# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Annotated, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.charts.base.view import KbnRangePalette
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel, OmitIfNone


class KbnDatatableColumnState(BaseRawVwModel):
    """Represents a column configuration in a datatable visualization.

    Maps to Kibana's ColumnState interface.
    """

    columnId: str | None = Field(default=None)
    'The ID of the column (references a metric or dimension).'
    width: Annotated[int | None, OmitIfNone()] = Field(default=None)
    'Column width in pixels.'
    hidden: Annotated[bool | None, OmitIfNone()] = Field(default=None)
    'Whether the column is hidden.'
    isTransposed: Annotated[bool | None, OmitIfNone()] = Field(default=None)
    'Whether the column is transposed.'
    isMetric: Annotated[bool | None, OmitIfNone()] = Field(default=None)
    'Whether this column represents a metric (true) or dimension (false).'
    oneClickFilter: Annotated[bool | None, OmitIfNone()] = Field(default=None)
    'Enable one-click filtering for this column.'
    alignment: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Text alignment for the column.'
    colorMode: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'How to apply colors to the column.'
    summaryRow: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Summary function to display at the bottom of the column.'
    summaryLabel: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Custom label for the summary row.'
    palette: Annotated[KbnRangePalette | None, OmitIfNone()] = Field(default=None)
    'Range-based color palette for numeric values.'


class KbnDatatableSortingState(BaseRawVwModel):
    """Represents the sorting configuration for a datatable visualization.

    Maps to Kibana's SortingState interface.
    """

    columnId: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'The ID of the column to sort by.'
    direction: Literal['asc', 'desc', 'none'] = Field(default='none')
    'Sort direction.'


class KbnDatatablePagingState(BaseRawVwModel):
    """Represents the pagination configuration for a datatable visualization.

    Maps to Kibana's PagingState interface.
    """

    size: int | None = Field(default=None)
    'Number of rows per page.'
    enabled: bool | None = Field(default=None)
    'Whether pagination is enabled.'


class KbnDatatableVisualizationState(BaseRawVwModel):
    """Represents the visualization state for a datatable chart.

    Maps to Kibana's DatatableVisualizationState interface.
    Note: Datatable does not use the layers structure like other visualizations.
    """

    columns: list[KbnDatatableColumnState] | None = Field(default=None)
    'List of column configurations.'
    layerId: str | None = Field(default=None)
    'The ID of the layer.'
    layerType: Literal['data'] = Field(default='data')
    "The type of layer (always 'data' for datatables)."
    sorting: Annotated[KbnDatatableSortingState | None, OmitIfNone()] = Field(default=None)
    'Optional sorting configuration.'
    rowHeight: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Row height mode.'
    headerRowHeight: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Header row height mode.'
    rowHeightLines: Annotated[int | None, OmitIfNone()] = Field(default=None)
    'Number of lines for custom row height.'
    headerRowHeightLines: Annotated[int | None, OmitIfNone()] = Field(default=None)
    'Number of lines for custom header row height.'
    paging: Annotated[KbnDatatablePagingState | None, OmitIfNone()] = Field(default=None)
    'Optional pagination configuration.'
    density: Annotated[str | None, OmitIfNone()] = Field(default=None)
    'Grid density setting.'
