# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT

"""Raw permissive KbnRaw* view models generated from kb_dashboard_core view models."""

from typing import Any, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnRawBasePanel, KbnRawBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnRawQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel


class KbnRawMarkdownSavedVisDataSearchSource(BaseRawVwModel):
    query: KbnRawQuery | None = None
    filter: list[Any] | None = None


class KbnRawMarkdownSavedVisData(BaseRawVwModel):
    aggs: list[Any] | None = Field(default=None)
    searchSource: KbnRawMarkdownSavedVisDataSearchSource | None = None


class KbnRawMarkdownSavedVisParams(BaseRawVwModel):
    fontSize: int | None = None
    openLinksInNewTab: bool | None = None
    markdown: str | None = None


class KbnRawMarkdownSavedVis(BaseRawVwModel):
    type: Literal['markdown'] = 'markdown'
    id: str | None = Field(default=None)
    title: str | None = Field(default=None)
    description: str | None = Field(default=None)
    params: KbnRawMarkdownSavedVisParams | None = Field(default=None)
    uiState: dict[str, Any] | None = Field(default=None)
    data: KbnRawMarkdownSavedVisData | None = Field(default=None)


class KbnRawMarkdownEmbeddableConfig(KbnRawBasePanelEmbeddableConfig):
    savedVis: KbnRawMarkdownSavedVis | None = None


class KbnRawMarkdownPanel(KbnRawBasePanel):
    """Represents a Markdown panel in the Kibana Kbn structure."""

    type: Literal['visualization'] = 'visualization'
    embeddableConfig: KbnRawMarkdownEmbeddableConfig | None = None
