# AUTO-GENERATED by scripts/codegen_raw_models.py — DO NOT EDIT
"""Permissive view models generated from kb_dashboard_core view models."""

from typing import Any, Literal

from pydantic import Field

from kb_dashboard_tools.decompile.kbn_raw_models.panels.view import KbnBasePanel, KbnBasePanelEmbeddableConfig
from kb_dashboard_tools.decompile.kbn_raw_models.queries.view import KbnQuery
from kb_dashboard_tools.decompile.kbn_raw_models.shared.view import BaseRawVwModel

KBN_MARKDOWN_DEFAULT_FONT_SIZE = 12
KBN_MARKDOWN_DEFAULT_OPEN_LINKS_IN_NEW_TAB = False


class KbnMarkdownSavedVisDataSearchSource(BaseRawVwModel):
    query: KbnQuery | None = None
    filter: list[Any] | None = None


class KbnMarkdownSavedVisData(BaseRawVwModel):
    aggs: list[Any] | None = Field(default=None)
    searchSource: KbnMarkdownSavedVisDataSearchSource | None = None


class KbnMarkdownSavedVisParams(BaseRawVwModel):
    fontSize: int | None = None
    openLinksInNewTab: bool | None = None
    markdown: str | None = None


class KbnMarkdownSavedVis(BaseRawVwModel):
    type: Literal['markdown'] = 'markdown'
    id: str | None = Field(default=None)
    title: str | None = Field(default=None)
    description: str | None = Field(default=None)
    params: KbnMarkdownSavedVisParams | None = Field(default=None)
    uiState: dict[str, Any] | None = Field(default=None)
    data: KbnMarkdownSavedVisData | None = Field(default=None)


class KbnMarkdownEmbeddableConfig(KbnBasePanelEmbeddableConfig):
    savedVis: KbnMarkdownSavedVis | None = None


class KbnMarkdownPanel(KbnBasePanel):
    """Represents a Markdown panel in the Kibana Kbn structure."""

    type: Literal['visualization'] = 'visualization'
    embeddableConfig: KbnMarkdownEmbeddableConfig | None = None
