---
name: Publish to PyPI
on:
  push:
    tags:
      - v*
concurrency:
  group: publish-pypi
  cancel-in-progress: false
jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/kb-dashboard-cli
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup just
        uses: extractions/setup-just@v2
      - name: Setup Python Environment
        uses: ./.github/actions/setup-python-env
      - name: Build kb-dashboard-core
        shell: bash
        run: just core build
      - name: Build kb-dashboard-tools
        shell: bash
        run: just tools build
      - name: Build kb-dashboard-lint
        shell: bash
        run: just lint build
      - name: Build kb-dashboard-docs
        shell: bash
        run: just docs build-package
      - name: Build kb-dashboard-cli
        shell: bash
        run: just cli build
      - name: Publish kb-dashboard-core to PyPI
        shell: bash
        run: just core publish
      - name: Publish kb-dashboard-tools to PyPI
        shell: bash
        run: just tools publish
      - name: Publish kb-dashboard-lint to PyPI
        shell: bash
        run: just lint publish
      - name: Publish kb-dashboard-docs to PyPI
        shell: bash
        run: just docs publish
      - name: Publish kb-dashboard-cli to PyPI
        shell: bash
        run: just cli publish
